### ISSUE TITLE
flaresolverr under github source: Exception: Error getting browser User-Agent. HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by garfield69** [FlareSolverr/FlareSolverr#826] opened 2023-07-19 19:09 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.2.2
- Last working FlareSolverr version: 3.2.2 when local chrome was 114
- Operating system: win10
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

my win10 chrome was auto-upgraded from 114 to 115 
after starting flaresolverr from source with `python src/flaresolverr.py` it now fails to start

i've run `pip install -r requirements.txt` but it did not help.

see log below

### Logged Error Messages

```text
C:\Users\Garfield69\Documents\GitHub\FlareSolverr>python src/flaresolverr.py
2023-07-20 06:58:28 INFO     FlareSolverr 3.2.2
2023-07-20 06:58:28 INFO     Testing web browser installation...
2023-07-20 06:58:28 INFO     Platform: Windows-10-10.0.19045-SP0
2023-07-20 06:58:28 INFO     Chrome / Chromium path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
2023-07-20 06:58:28 INFO     Chrome / Chromium major version: 115
2023-07-20 06:58:28 INFO     Launching web browser...
Traceback (most recent call last):
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\utils.py", line 218, in get_user_agent
    driver = get_webdriver()
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\utils.py", line 97, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\undetected_chromedriver\patcher.py", line 158, in auto
    release = self.fetch_release_number()
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\undetected_chromedriver\patcher.py", line 222, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "C:\Users\Garfield69\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Garfield69\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\Garfield69\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\Garfield69\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\Garfield69\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Garfield69\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\utils.py", line 222, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. HTTP Error 404: Not Found
```

**Comment by ilike2burnthing** [comment] 2023-07-19 22:32
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1259#issuecomment-1546736798

Explanation here - https://github.com/FlareSolverr/FlareSolverr/issues/827

**Comment by peterbysh** [comment] 2023-07-26 12:01
Hi,

Experiencing this same issue on linux, Flaresolverr installed from github, tracking it down it looks like the issue is the inexistence of https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115

**Comment by AnthonyBe** [comment] 2023-07-29 01:20
> Hi,
> 
> Experiencing this same issue on linux, Flaresolverr installed from github, tracking it down it looks like the issue is the inexistence of https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115

Yep, as documented in this linked issue - https://github.com/FlareSolverr/FlareSolverr/issues/827

**Comment by ngosang** [comment] 2023-08-02 18:47
This is fixed in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.0

**Closed by ngosang** 2023-08-02 18:47 UTC
Labels: help wanted, Needs Investigation

**Comment by garfield69** [comment] 2023-08-02 20:42
\o/
