### ISSUE TITLE
FlareSolverr issue to complete CloudFlare challenge

### ISSUE THREAD

**Issue by davidihii** [FlareSolverr/FlareSolverr#1286] opened 2024-07-25 14:03 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: ??? first install
- Operating system: Ubuntu 22.04.4 LTS (LXC proxmox container)
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: yes
- If using captcha solver, which one: I've set "hcaptcha" in docker compose file
- URL to test this issue: ygg.re
```

### Description

Hi, still the same problem not resolved with YGG.
Before @ilike2burnthing close it :
- I've read the 1036 issue, check that ssl options was not commented in utils.py
- I've read the troubleshooting topic and done everything : it running on docker and Jackett as well on the same host, with no ipv6 enabled on the host, tried iDope and Torrent[CORE] on Jackett the test passed.
- When i've done the curl command for others torrent indexer it worked, i tried petsathome.com as well it worked.

Other information if i start google-chrome from ssh session I can't pass the cloudflare "i'm human" check, maybe the issue with ygg is related.
You must know that ygg is working perfectly on browsers.

Here is the FlareSolver web page output :
```json
{
  "msg": "FlareSolverr is ready!",
  "version": "3.3.21",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}
```
Here is the curl for ygg.re output :
```bash
curl -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{
  "cmd": "request.get",
  "url": "https://ygg.re/",
  "maxTimeout": 100000
}'
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 100.0 seconds.", "startTimestamp": 1721915203868, "endTimestamp": 1721915306761, "version": "3.3.21"}
```

And the logs from FlareSolverr :
```bash
2024-07-25 14:35:48 INFO     ReqId 125513093875456 172.21.0.1 POST http://localhost:8191/v1 200 OK
2024-07-25 14:46:43 INFO     ReqId 125513083389696 Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://ygg.re/', 'maxTimeout': 100000}
2024-07-25 14:46:43 DEBUG    ReqId 125513083389696 Launching web browser...
2024-07-25 14:46:43 DEBUG    ReqId 125513083389696 Started executable: `/app/chromedriver` in a child process with pid: 2874
2024-07-25 14:46:45 DEBUG    ReqId 125513083389696 New instance of webdriver has been created to perform the request
2024-07-25 14:46:45 DEBUG    ReqId 125513051932416 Navigating to... https://ygg.re/
2024-07-25 14:46:49 DEBUG    ReqId 125513051932416 Response HTML:
<html lang="en-US" dir="ltr"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,init"
[...]>
2024-07-25 14:46:49 INFO     ReqId 125513051932416 Challenge detected. Title found: Just a moment...
2024-07-25 14:46:49 DEBUG    ReqId 125513051932416 Waiting for title (attempt 1): Just a moment...
[...]
2024-07-25 14:48:22 DEBUG    ReqId 125513051932416 Try to find the Cloudflare verify checkbox...
2024-07-25 14:48:22 DEBUG    ReqId 125513051932416 Cloudflare verify checkbox not found on the page.
2024-07-25 14:48:22 DEBUG    ReqId 125513051932416 Try to find the Cloudflare 'Verify you are human' button...
2024-07-25 14:48:23 DEBUG    ReqId 125513051932416 The Cloudflare 'Verify you are human' button not found on the page.
2024-07-25 14:48:25 DEBUG    ReqId 125513051932416 Waiting for title (attempt 31): Just a moment...
2024-07-25 14:48:26 DEBUG    ReqId 125513083389696 A used instance of webdriver has been destroyed
2024-07-25 14:48:26 ERROR    ReqId 125513083389696 Error: Error solving the challenge. Timeout after 100.0 seconds.
2024-07-25 14:48:26 DEBUG    ReqId 125513083389696 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 100.0 seconds.', 'startTimestamp': 1721915203868, 'endTimestamp': 1721915306761, 'version': '3.3.21'}
2024-07-25 14:48:26 INFO     ReqId 125513083389696 Response in 102.893 s
2024-07-25 14:48:26 INFO     ReqId 125513083389696 172.21.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```
Could you please provide a real fix.

**Comment by cuebit** [comment] 2024-07-25 15:14
Duplicate of #1253

**Closed** 2024-07-25 15:34 UTC
Labels: duplicate
