### ISSUE TITLE
Flaresolverr and Jackett don't work with torrentleech.pl

### ISSUE THREAD

**Issue by PrzemekSkw** [FlareSolverr/FlareSolverr#1285] opened 2024-07-25 09:02 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:`3.3.21`
- Jackett Version: `v0.22.364`
- Last working FlareSolverr version:?
- Operating system: `Unraid 6.12.11`
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint):`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Are you using a VPN: [yes] `wireguard`
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one: -
- URL to test this issue: ?
```

### Description

There's no captcha to put numbers as always was:
![image](https://github.com/user-attachments/assets/06601705-73fd-43e7-a37d-5bdd27a834cc)

![image](https://github.com/user-attachments/assets/d44ee2b8-efef-4eb5-9825-528760d7c22f)

Torrentleech.pl don't work in Jackett or Prowlarr.

### Logged Error Messages

```text
2024-07-25 08:38:19 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:39:19 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:39:38 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://torrentleech.pl/login.php'}
2024-07-25 08:39:41 INFO     Challenge detected. Title found: Just a moment...
2024-07-25 08:40:19 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:40:34 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-07-25 08:40:34 INFO     Response in 55.735 s
2024-07-25 08:40:34 INFO     172.17.0.1 POST http://192.168.0.208:8191/v1 500 Internal Server Error
2024-07-25 08:41:19 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:41:20 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://torrentleech.pl/login.php'}
2024-07-25 08:41:22 INFO     Challenge detected. Title found: Just a moment...
2024-07-25 08:42:16 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-07-25 08:42:16 INFO     Response in 55.665 s
2024-07-25 08:42:16 INFO     172.17.0.1 POST http://192.168.0.208:8191/v1 500 Internal Server Error
2024-07-25 08:42:19 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:43:19 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:44:19 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:44:43 INFO     FlareSolverr 3.3.21
2024-07-25 08:44:43 INFO     Testing web browser installation...
2024-07-25 08:44:43 INFO     Platform: Linux-6.1.99-Unraid-x86_64-with-glibc2.31
2024-07-25 08:44:43 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-07-25 08:44:43 INFO     Chrome / Chromium major version: 120
2024-07-25 08:44:43 INFO     Launching web browser...
2024-07-25 08:44:44 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024-07-25 08:44:44 INFO     Test successful!
2024-07-25 08:44:44 INFO     Serving on http://0.0.0.0:8191
2024-07-25 08:45:07 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://torrentleech.pl/login.php'}
2024-07-25 08:45:09 INFO     Challenge detected. Title found: Just a moment...
2024-07-25 08:45:19 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:46:02 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-07-25 08:46:02 INFO     Response in 55.667 s
2024-07-25 08:46:02 INFO     172.17.0.1 POST http://192.168.0.208:8191/v1 500 Internal Server Error
2024-07-25 08:46:20 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:47:20 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:48:20 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:48:43 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://torrentleech.pl/login.php'}
2024-07-25 08:48:45 INFO     Challenge detected. Title found: Just a moment...
2024-07-25 08:49:20 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:49:39 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-07-25 08:49:39 INFO     Response in 55.67 s
2024-07-25 08:49:39 INFO     172.17.0.1 POST http://192.168.0.208:8191/v1 500 Internal Server Error
2024-07-25 08:50:20 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
2024-07-25 08:51:20 INFO     172.17.0.1 GET http://192.168.0.208:8191/ 200 OK
```
```


### Screenshots

_No response_

**Comment by cuebit** [comment] 2024-07-25 15:19
Duplicate of #1253

**Closed** 2024-07-25 15:53 UTC
