### ISSUE TITLE
Error solving the challenge

### ISSUE THREAD

**Issue by researchersec** [FlareSolverr/FlareSolverr#1175] opened 2024-05-04 12:23 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.17
- Last working FlareSolverr version:
- Operating system: ubuntu Linux-6.5.0-1018-azure-x86_64-with-glibc2.31
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue: https://datacvr.virk.dk/
```

### Description

Do I need to configure further? Im using the latest build

```text
- name: Pull Docker image
      run: docker pull ghcr.io/flaresolverr/flaresolverr:latest

    - name: Run FlareSolverr container
      run: |
        docker run -d --name flaresolverr-container -p 8191:8191 \
        -e LOG_LEVEL=debug \
        -e LOG_HTML=true \
        -e TZ=Europe/Copenhagen \
        -e BROWSER_TIMEOUT=200000 \
        -e LANG=en_US \
        ghcr.io/flaresolverr/flaresolverr:latest
```
### Logged Error Messages

```text
2024-05-04 14:13:15 INFO     ReqId 139978190403392 FlareSolverr 3.3.17
2024-05-04 14:13:15 DEBUG    ReqId 139978190403392 Debug log enabled
2024-05-04 14:13:15 INFO     ReqId 139978190403392 Testing web browser installation...
2024-05-04 14:13:15 INFO     ReqId 139978190403392 Platform: Linux-6.5.0-1018-azure-x86_64-with-glibc2.31
2024-05-04 14:13:15 INFO     ReqId 139978190403392 Chrome / Chromium path: /usr/bin/chromium
2024-05-04 14:13:16 INFO     ReqId 139978190403392 Chrome / Chromium major version: 120
2024-05-04 14:13:16 INFO     ReqId 139978190403392 Launching web browser...
2024-05-04 14:13:16 DEBUG    ReqId 139978190403392 Launching web browser...
version_main cannot be converted to an integer
2024-05-04 14:13:16 DEBUG    ReqId 139978190403392 Started executable: `/app/chromedriver` in a child process with pid: 31
2024-05-04 14:13:16 INFO     ReqId 139978190403392 FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024-05-04 14:13:16 INFO     ReqId 139978190403392 Test successful!
2024-05-04 14:13:16 INFO     ReqId 139978190403392 Serving on http://0.0.0.0:8191
2024-05-04 14:13:35 INFO     ReqId 139978157844224 Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://datacvr.virk.dk/soegeresultater?fritekst=*&antalAnsatte=ANTAL_1000_999999&size=10', 'maxTimeout': 90000}
2024-05-04 14:13:35 DEBUG    ReqId 139978157844224 Launching web browser...
version_main cannot be converted to an integer
2024-05-04 14:13:35 DEBUG    ReqId 139978157844224 Started executable: `/app/chromedriver` in a child process with pid: 191
2024-05-04 14:13:36 DEBUG    ReqId 139978157844224 New instance of webdriver has been created to perform the request
2024-05-04 14:13:36 DEBUG    ReqId 139977883121408 Navigating to... https://datacvr.virk.dk/soegeresultater?fritekst=*&antalAnsatte=ANTAL_1000_999999&size=10
2024-05-04 14:13:37 DEBUG    ReqId 139977883121408 Response HTML:
<html lang="en-US" class="lang-en-us"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .big-button,body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cD
2024-05-04 14:13:37 INFO     ReqId 139977883121408 Challenge detected. Title found: Just a moment...
2024-05-04 14:13:37 DEBUG    ReqId 139977883121408 Waiting for title (attempt 1): Just a moment...
2024-05-04 14:13:38 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:13:38 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:13:38 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:13:38 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:13:38 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:13:40 DEBUG    ReqId 139977883121408 Waiting for title (attempt 2): Just a moment...
2024-05-04 14:13:41 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:13:41 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:13:42 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox found and clicked!
2024-05-04 14:13:42 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:13:42 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:13:44 DEBUG    ReqId 139977883121408 Waiting for title (attempt 3): Just a moment...
2024-05-04 14:13:45 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:13:45 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:13:45 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:13:45 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:13:45 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:13:47 DEBUG    ReqId 139977883121408 Waiting for title (attempt 4): Just a moment...
2024-05-04 14:13:48 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:13:48 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:13:49 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox found and clicked!
2024-05-04 14:13:49 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:13:49 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:13:51 DEBUG    ReqId 139977883121408 Waiting for title (attempt 5): Just a moment...
2024-05-04 14:13:52 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:13:52 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:13:52 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:13:52 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:13:52 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:13:54 DEBUG    ReqId 139977883121408 Waiting for title (attempt 6): Just a moment...
2024-05-04 14:13:55 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:13:55 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:13:55 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:13:55 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:13:55 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:13:57 DEBUG    ReqId 139977883121408 Waiting for title (attempt 7): Just a moment...
2024-05-04 14:13:58 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:13:58 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:13:58 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:13:58 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:13:58 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:00 DEBUG    ReqId 139977883121408 Waiting for title (attempt 8): Just a moment...
2024-05-04 14:14:01 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:01 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:02 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox found and clicked!
2024-05-04 14:14:02 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:02 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:04 DEBUG    ReqId 139977883121408 Waiting for title (attempt 9): Just a moment...
2024-05-04 14:14:05 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:05 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:05 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:05 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:05 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:07 DEBUG    ReqId 139977883121408 Waiting for title (attempt 10): Just a moment...
2024-05-04 14:14:08 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:08 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:08 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:08 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:08 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:10 DEBUG    ReqId 139977883121408 Waiting for title (attempt 11): Just a moment...
2024-05-04 14:14:11 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:11 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:11 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:11 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:11 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:13 DEBUG    ReqId 139977883121408 Waiting for title (attempt 12): Just a moment...
2024-05-04 14:14:14 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:14 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:15 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox found and clicked!
2024-05-04 14:14:15 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:15 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:17 DEBUG    ReqId 139977883121408 Waiting for title (attempt 13): Just a moment...
2024-05-04 14:14:18 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:18 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:18 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:18 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:18 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:20 DEBUG    ReqId 139977883121408 Waiting for title (attempt 14): Just a moment...
2024-05-04 14:14:21 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:21 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:21 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:21 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:21 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:23 DEBUG    ReqId 139977883121408 Waiting for title (attempt 15): Just a moment...
2024-05-04 14:14:24 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:24 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:24 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:24 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:24 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:26 DEBUG    ReqId 139977883121408 Waiting for title (attempt 16): Just a moment...
2024-05-04 14:14:27 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:27 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:27 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:27 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:27 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:29 DEBUG    ReqId 139977883121408 Waiting for title (attempt 17): Just a moment...
2024-05-04 14:14:30 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:30 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:30 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:30 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:30 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:32 DEBUG    ReqId 139977883121408 Waiting for title (attempt 18): Just a moment...
2024-05-04 14:14:33 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:33 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:33 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:33 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:33 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:35 DEBUG    ReqId 139977883121408 Waiting for title (attempt 19): Just a moment...
2024-05-04 14:14:36 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:36 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:37 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox found and clicked!
2024-05-04 14:14:37 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:37 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:39 DEBUG    ReqId 139977883121408 Waiting for title (attempt 20): Just a moment...
2024-05-04 14:14:40 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:40 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:40 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:40 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:40 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:42 DEBUG    ReqId 139977883121408 Waiting for title (attempt 21): Just a moment...
2024-05-04 14:14:43 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:43 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:43 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:43 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:43 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:45 DEBUG    ReqId 139977883121408 Waiting for title (attempt 22): Just a moment...
2024-05-04 14:14:46 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:46 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:46 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:46 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:46 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:48 DEBUG    ReqId 139977883121408 Waiting for title (attempt 23): Just a moment...
2024-05-04 14:14:49 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:49 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:49 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:49 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:49 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:51 DEBUG    ReqId 139977883121408 Waiting for title (attempt 24): Just a moment...
2024-05-04 14:14:52 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:52 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:52 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:52 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:52 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:54 DEBUG    ReqId 139977883121408 Waiting for title (attempt 25): Just a moment...
2024-05-04 14:14:55 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:55 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:55 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:14:55 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:55 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:14:57 DEBUG    ReqId 139977883121408 Waiting for title (attempt 26): Just a moment...
2024-05-04 14:14:58 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:14:58 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:14:59 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox found and clicked!
2024-05-04 14:14:59 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:14:59 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:15:01 DEBUG    ReqId 139977883121408 Waiting for title (attempt 27): Just a moment...
2024-05-04 14:15:02 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:15:02 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:15:02 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:15:02 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:15:02 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:15:04 DEBUG    ReqId 139977883121408 Waiting for title (attempt 28): Just a moment...
2024-05-04 14:15:05 DEBUG    ReqId 139977883121408 Timeout waiting for selector
2024-05-04 14:15:05 DEBUG    ReqId 139977883121408 Try to find the Cloudflare verify checkbox...
2024-05-04 14:15:05 DEBUG    ReqId 139977883121408 Cloudflare verify checkbox not found on the page.
2024-05-04 14:15:05 DEBUG    ReqId 139977883121408 Try to find the Cloudflare 'Verify you are human' button...
2024-05-04 14:15:05 DEBUG    ReqId 139977883121408 The Cloudflare 'Verify you are human' button not found on the page.
2024-05-04 14:15:06 DEBUG    ReqId 139978157844224 A used instance of webdriver has been destroyed
2024-05-04 14:15:06 ERROR    ReqId 139978157844224 Error: Error solving the challenge. Timeout after 90.0 seconds.
2024-05-04 14:15:06 DEBUG    ReqId 139978157844224 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 90.0 seconds.', 'startTimestamp': 1714824815816, 'endTimestamp': 1714824906648, 'version': '3.3.17'}
2024-05-04 14:15:06 INFO     ReqId 139978157844224 Response in 90.832 s
2024-05-04 14:15:06 INFO     ReqId 139978157844224 172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```

**Comment by TayZ3r** [comment] 2024-05-04 14:12
Hey, I'm not a contributor, but this is a duplicate of #1036 
Still no release to fix it officially, but #1163 seems to work in 95%

**Closed** 2024-05-05 02:09 UTC
