### ISSUE TITLE
Flaresolverr timing out. Ip not banned

### ISSUE THREAD

**Issue by Zeks** [FlareSolverr/FlareSolverr#366] opened 2022-04-17 20:16 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**:
* **Last working FlareSolverr version**:
* **Operating system**:
* **Are you using Docker**: [yes/no]
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes/no]
* **Are you using Captcha Solver:** [yes/no]
* **If using captcha solver, which one:**
* **URL to test this issue:** https://www.fanfiction.net/u/4963392

### Description

I can still access the site as normal on the pc that shares the IP address.

The timeouts don't happen always but they happen more often than not. tested this both against the older flaresolverr version I was using previously and 2.2.4

### Logged Error Messages

```text
2022-04-17T20:13:47+00:00 INFO REQ-1 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://www.fanfiction.net/u/4963392","maxTimeout":60000}
2022-04-17T20:13:49+00:00 INFO REQ-1 Cloudflare detected
2022-04-17T20:14:49+00:00 ERROR REQ-1 Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=60000 (ms)
2022-04-17T20:14:49+00:00 INFO REQ-1 Response in 61.696 s
2022-04-17T20:14:49+00:00 ERROR REQ-1 Unexpected error: Error: Protocol error (Network.getCookies): Session closed. Most likely the page has been closed.
2022-04-17T20:14:57+00:00 INFO REQ-2 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://www.fanfiction.net/u/4963392","maxTimeout":60000}
2022-04-17T20:14:59+00:00 INFO REQ-2 Cloudflare detected
2022-04-17T20:15:58+00:00 ERROR REQ-2 Unexpected error: Error: Protocol error (Network.getCookies): Session closed. Most likely the page has been closed.
2022-04-17T20:15:59+00:00 ERROR REQ-2 Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=60000 (ms)
2022-04-17T20:15:59+00:00 INFO REQ-2 Response in 61.601s
```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment] 2022-04-19 21:18
Please don't remove the template. Provide the missing requested information.

**Comment by Axzanaeb** [comment] 2022-04-22 09:32
Having the exact same problem with another website.

**Comment by Neferites** [comment] 2022-04-22 12:43
Hello,
Same issue here, with ygg.
Regards

**Comment by ilike2burnthing** [comment] 2022-04-22 13:38
That's not the same error, please open a new issue and provide the information requested.

**Comment by ngosang** [comment] 2022-04-24 17:46
I having this issue in 1337 and in zooqle. I can not fix it for now.

**Comment by yi-ge** [comment] 2022-05-12 02:30
I have the same problem.

**Comment by realivanjx** [comment] 2022-07-30 16:00
in my case it eventually solved after some 250-300 secs so try to increase the timeout somehow (im using FlareSolverrSharp)

**Comment by ngosang** [comment] 2022-07-30 22:12
I'm going to close this issue since I can not reproduce it anymore. Test with the latest releases:

FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5
Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496

**Closed by ngosang** 2022-07-30 22:12 UTC
Labels: more information needed
