### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent):  unable to process the request

### ISSUE THREAD

**Issue by DaGreenX** [FlareSolverr/FlareSolverr#1247] opened 2024-07-04 20:05 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.2.1
- Last working FlareSolverr version: 3.3.2.1
- Operating system: DSM 7.2.1
- Are you using Docker: [yes/no] Yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] yes
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] yes
- If using captcha solver, which one: HARVESTER
- URL to test this issue:
```

### Description

FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.

thx for helping 

### Logged Error Messages

```text
024-07-04 20:00:16 INFO     192.168.1.44 POST http://192.168.1.44:8191/v1 500 Internal Server Error
2024/07/04 22:00:16	stdout	2024-07-04 20:00:16 INFO     Response in 92.25 s
2024/07/04 22:00:16	stdout	2024-07-04 20:00:16 ERROR    Error: Error solving the challenge. Timeout after 90.0 seconds.
2024/07/04 21:58:50	stdout	2024-07-04 19:58:50 INFO     Challenge detected. Title found: Just a moment...
2024/07/04 21:58:44	stdout	2024-07-04 19:58:44 INFO     Incoming request => POST /v1 body: {'maxTimeout': 90000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?do=search&order=desc&sort=publish_date&category=all'}
2024/07/04 21:56:24	stdout	2024-07-04 19:56:24 INFO     Serving on http://0.0.0.0:8191
2024/07/04 21:56:24	stdout	2024-07-04 19:56:24 INFO     Test successful!
2024/07/04 21:56:24	stdout	2024-07-04 19:56:24 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024/07/04 21:56:17	stdout	2024-07-04 19:56:17 INFO     Launching web browser...
2024/07/04 21:56:17	stdout	2024-07-04 19:56:17 INFO     Chrome / Chromium major version: 120
2024/07/04 21:56:06	stdout	2024-07-04 19:56:06 INFO     Chrome / Chromium path: /usr/bin/chromium
2024/07/04 21:56:06	stdout	2024-07-04 19:56:06 INFO     Platform: Linux-4.4.302+-x86_64-with-glibc2.31
2024/07/04 21:56:06	stdout	2024-07-04 19:56:06 INFO     Testing web browser installation...
2024/07/04 21:56:06	stdout	2024-07-04 19:56:06 INFO     FlareSolverr 3.3.21
```

**Comment by sanchobouillant** [comment] 2024-07-04 21:03
The admin is going to close the ticket. Supposedly, there is a solution, but it doesn't work. It is impossible to create a ticket for this issue and impossible to get support for "the solution."

**Comment by DaGreenX** [comment] 2024-07-04 21:21
Why? Doesn't it make sense?
I read something with 3.3.2.0, but it doesn't work.

**Comment by sanchobouillant** [comment] 2024-07-05 06:58
The solution seems too obvious to him, but nobody understands it. I tested the Docker image that should work and also added some lines of Python code, but it's still the same on my end. I think it comes from Cloudflare. On my residential IP, it works, but on my VPS, it doesn't. Flare no longer seems "undetectable"

**Comment by sanchobouillant** [comment] 2024-07-05 07:42
(#1163)

**Comment by DaGreenX** [comment] 2024-07-05 07:50
> The solution seems too obvious to him, but nobody understands it.

🙈

honestly, if it's that obvious, we shouldn't have to tinker.
Cases like this are frequent, but they are always solved by updating FlareSolver or jacket. Or because CloudFlare gets excited for a few days. But here.... everything is up to date, I don't understand what's going on.

**Comment by DaGreenX** [comment] 2024-07-05 07:51
can you share your FlareSolver's settings?

**Comment by DaGreenX** [comment] 2024-07-05 08:41
so mine is in Gb-GB even though I'm actually French. I wanted to test in Fr-FR because I remember a case like that. I'm not at home this morning, and my Synology is behind a VPN. I'll try it later.

**Comment by DaGreenX** [comment] 2024-07-05 08:46
Did you tried this ? : https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

**Comment by TayZ3r** [comment] 2024-07-05 11:09
Duplicate of #1036

**Comment by TayZ3r** [comment] 2024-07-05 11:15
> That's exactly it your problem is going to be closed by saying that it's a duplication and that you didn't look at the old posts before asking your question, when everyone else did, plus ilike2burnthing if you see this message.
> 
> This problem #1246 is the same as ours, it simply appears when your Flaresolverr has the language set to "fr_FR".
> 
> And I can assure you that even amen having read all the messages on the old posts nothing answers the problem and I'm not the only one in this case.

ilike2burnthing answered you [here](https://github.com/FlareSolverr/FlareSolverr/issues/1246#issuecomment-2209113234) and you're still complaining. Yes, the issue #1036 is not resolved, yes it sometimes get a fix but not for long and yes, they are trying to solve the issue, see the #1163 PR. Just stop posting everywhere that it doesn't work for you. It works for nobody.

**Comment by sanchobouillant** [comment] 2024-07-05 12:38
Leave this ticket open so that we can complain here. Maybe someone will come up with an idea through complaining. When the ticket is closed, people come and recreate it; at least when it is open, people understand. Tickets are closed with the information "It works on the other ticket," but apparently, no one understands that it is in progress.

**Comment by ilike2burnthing** [comment] 2024-07-06 01:56
If people aren't going to read the pinned issue before posting, why would they read this random one? Again, the PR is open for discussion (NOT complaining or 'same here' spam).

**Closed by ilike2burnthing** 2024-07-06 01:56 UTC
