### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): Exception: System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by nest78** [FlareSolverr/FlareSolverr#955] opened 2023-11-09 18:06 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.7
- Last working FlareSolverr version:3.3.6
- Operating system:Windows 11
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

impossible to connect jackett

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (yggtorrent): Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing. ---> System.TimeoutException: The operation was canceled. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: L’opération d’entrée/sortie a été abandonnée en raison de l’arrêt d’un thread ou à la demande d’une application.. ---> System.Net.Sockets.SocketException (995): L’opération d’entrée/sortie a été abandonnée en raison de l’arrêt d’un thread ou à la demande d’une application. --- End of inner exception stack trace --- at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token) at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async) at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpReq
```

**Comment by ilike2burnthing** [comment] 2023-11-09 21:34
Follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

Extend the timeout to `100000`, see if that makes a difference.

If not, do you have the same issue with iDope, TorrentQQ, and Torrent[CORE]?

**Comment by nest78** [comment] 2023-11-10 05:34
Same problem with timeout to 100000

**Comment by nest78** [comment] 2023-11-10 05:43
2023-11-10 06:40:13 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?do=search&order=desc&sort=publish_date&category=all'}
2023-11-10 06:40:15 INFO     Challenge detected. Selector found: #challenge-spinner
2023-11-10 06:41:55 ERROR    Error: Error solving the challenge. Timeout after 100.0 seconds.
2023-11-10 06:41:55 INFO     Response in 102.319 s
2023-11-10 06:41:55 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error

**Comment by skyfyx** [comment] 2023-11-10 11:22
I have the same Issue: 
`
2023-11-10 11:57:00 INFO Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?do=search&order=desc&sort=publish_date&category=all'}

2023-11-10 11:57:01 INFO Challenge detected. Selector found: #challenge-spinner
2023-11-10 11:58:41 ERROR Error: Error solving the challenge. Timeout after 100.0 seconds.
2023-11-10 11:58:41 INFO Response in 101.049 s
2023-11-10 11:58:41 INFO 127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
`
I use the windows Executable version.

**Comment by ilike2burnthing** [comment] 2023-11-10 11:55
> If not, do you have the same issue with iDope, TorrentQQ, and Torrent[CORE]?

**Comment by nest78** [comment] 2023-11-10 14:28
test ok for idope et Torrent Core

**Comment by Akashi2020** [comment] 2023-11-10 16:00
![Capture d’écran 2023-11-10 165935](https://github.com/FlareSolverr/FlareSolverr/assets/72036990/356cf435-a163-487d-a1c8-3629433f8b33)

Here's the error I get on my side, I'm running a Windows executable.

**Comment by zehelh** [comment] 2023-11-10 17:13
same issue here.. wait for solvin' :)

**Comment by ilike2burnthing** [comment] 2023-11-10 19:50
Akashi, are you purposefully running FlareSolverr on port 55301?

**Comment by ilike2burnthing** [comment] 2023-11-10 19:52
Closing as duplicate of other YGG issues. Issue maybe be IP/geo specific. Beyond just basic troubleshooting, can only recommend trying several different proxy/VPN servers from different countries.

**Closed by ilike2burnthing** 2023-11-10 19:52 UTC
Labels: more information needed
