### ISSUE TITLE
animetorrents.me verify loop

### ISSUE THREAD

**Issue by GR3ee3N** [FlareSolverr/FlareSolverr#1248] opened 2024-07-05 15:57 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: 
- Operating system: Ubuntu 22.04
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://animetorrents.me/login.php
```

### Description

Trying to add AnimeTorrents in Prowlarr

I checked with headful mode and it's looping on the Verify you are Human page endlessly until timeout is reached.

Accessing https://animetorrents.me/login.php on the same machine and browser manually i can easily get past the challenge.

### Logged Error Messages

```text
2024-07-05 14:43:20 INFO     Incoming request => POST /v1 body: {'maxTimeout': 180000, 'cmd': 'request.get', 'url': 'https://animetorrents.me/login.php', 'proxy': {}}
2024-07-05 14:43:22 INFO     Challenge detected. Title found: Just a moment...
2024-07-05 14:46:23 ERROR    Error: Error solving the challenge. Timeout after 180.0 seconds.
2024-07-05 14:46:23 INFO     Response in 183.072 s
2024-07-05 14:46:23 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```

**Comment by TayZ3r** [comment] 2024-07-05 18:48
Duplicate of #1036 (again and again ...). It's still not fixed.

**Closed** 2024-07-06 02:00 UTC
