### ISSUE TITLE
[Docker] TimeoutError while starting

### ISSUE THREAD

**Issue by Durantz** [FlareSolverr/FlareSolverr#288] opened 2022-01-31 17:13 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: v. 2.2.0
* **Last working FlareSolverr version**: none
* **Operating system**: Debian
* **Are you using Docker**:  yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** [yes/no] 
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

I cannot manage to make FlareSolverr working in Docker on Raspberry Pi 4. It tries to test web installation and throws an exception.
I've also passed 10 sec timeout to Env variables but it wasn't effective.
The logs keep reporting that the system is too slow but actually the CPU is not impacted at all by this and so is the memory
Also, I've no CPU limits on the container.

### Logged Error Messages

2022-01-31T17:09:50+00:00 INFO FlareSolverr v2.2.0
2022-01-31T17:09:50+00:00 DEBUG Debug log enabled
2022-01-31T17:09:50+00:00 INFO Testing web browser installation...
2022-01-31T17:09:50+00:00 DEBUG FlareSolverr user home directory is OK: /home/node
2022-01-31T17:09:50+00:00 DEBUG Test URL: https://www.google.com
2022-01-31T17:09:50+00:00 DEBUG Launching web browser...
2022-01-31T17:10:00+00:00 ERROR TimeoutError: Timed out after 10000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.
    at Timeout.onTimeout (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:240:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-01-31T17:10:01+00:00 ERROR It seems that the system is too slow to run FlareSolverr. 
    If you are running with Docker, try to remove CPU limits in the container. 
    If not, try setting the 'BROWSER_TIMEOUT' environment variable and the 'maxTimeout' parameter to higher values.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment] 2022-01-31 17:15
Try a bigger value in BROWSER_TIMEOUT, for example 60000

**Comment by Durantz** [comment] 2022-01-31 18:50
Hi @ngosang,
This is happening now
```
2022-01-31T18:48:19+00:00 INFO FlareSolverr v2.2.0
2022-01-31T18:48:19+00:00 DEBUG Debug log enabled
2022-01-31T18:48:19+00:00 INFO Testing web browser installation...
2022-01-31T18:48:19+00:00 DEBUG FlareSolverr user home directory is OK: /home/node
2022-01-31T18:49:12+00:00 ERROR ErrorEvent {
2022-01-31T18:48:19+00:00 DEBUG Launching web browser...
2022-01-31T18:48:19+00:00 DEBUG Test URL: https://www.google.com
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _closeFrameReceived: false,
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _req: null,
    _url: 'ws://localhost:43981/devtools/browser/9e387ec0-89ee-4889-ba69-bc1df7918a86',
    _redirects: 0,
    [Symbol(kCapture)]: false
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: getaddrinfo EAI_AGAIN localhost
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'localhost'
  },
  [Symbol(kMessage)]: 'getaddrinfo EAI_AGAIN localhost'
}
```

**Comment by ngosang** [comment] 2022-02-06 10:09
The second error is different. It's caused because FlareSolverr can not resolve the DNS for www.google.com. If that domain is blocked in your country you can set the environment variable `TEST_URL=https://www.google.com/` to use another domain. Probably you have something wrong in your network.

**Comment by jeanfrancoislarente** [comment] 2022-02-09 18:40
I'm struggling with the same issue above @ngosang ... I'm launching from within a docker-compose file. I can confirm that it's a network issue (can't ping anything from within the running container) but I'm struggling to see what I can change to make it work.

Any help (although likely a bit out of scope) is definitely appreciated!

```
version: "3.2"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_HTML=${LOG_HTML:-true}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped

networks:
  t2_proxy:
      name: t2_proxy
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.90.0/24
  default:
    driver: bridge
```

```
 2022-02-09T13:36:57-05:00 INFO FlareSolverr v2.2.1
flaresolverr        | 2022-02-09T13:36:57-05:00 DEBUG Debug log enabled
flaresolverr        | 2022-02-09T13:36:57-05:00 INFO Testing web browser installation...
flaresolverr        | 2022-02-09T13:36:57-05:00 DEBUG FlareSolverr user home directory is OK: /home/node
flaresolverr        | 2022-02-09T13:36:57-05:00 DEBUG Test URL: https://www.google.com
flaresolverr        | 2022-02-09T13:36:57-05:00 DEBUG Creating new session...
flaresolverr        | 2022-02-09T13:36:57-05:00 DEBUG Launching web browser...
flaresolverr        | 2022-02-09T13:37:08-05:00 ERROR ErrorEvent {
flaresolverr        |   [Symbol(kTarget)]: WebSocket {
flaresolverr        |     _events: [Object: null prototype] { open: [Function], error: [Function] },
flaresolverr        |     _eventsCount: 2,
flaresolverr        |     _maxListeners: undefined,
flaresolverr        |     _binaryType: 'nodebuffer',
flaresolverr        |     _closeCode: 1006,
flaresolverr        |     _closeFrameReceived: false,
flaresolverr        |     _closeFrameSent: false,
flaresolverr        |     _closeMessage: <Buffer >,
flaresolverr        |     _closeTimer: null,
flaresolverr        |     _extensions: {},
flaresolverr        |     _protocol: '',
flaresolverr        |     _readyState: 3,
flaresolverr        |     _receiver: null,
flaresolverr        |     _sender: null,
flaresolverr        |     _socket: null,
flaresolverr        |     _bufferedAmount: 0,
flaresolverr        |     _isServer: false,
flaresolverr        |     _redirects: 0,
flaresolverr        |     _url: 'ws://localhost:40347/devtools/browser/28a61ce7-2c51-4c40-90c8-dd4d82230a75',
flaresolverr        |     _req: null,
flaresolverr        |     [Symbol(kCapture)]: false
flaresolverr        |   },
flaresolverr        |   [Symbol(kType)]: 'error',
flaresolverr        |   [Symbol(kError)]: Error: getaddrinfo EAI_AGAIN localhost
flaresolverr        |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
flaresolverr        |     errno: -3001,
flaresolverr        |     code: 'EAI_AGAIN',
flaresolverr        |     syscall: 'getaddrinfo',
flaresolverr        |     hostname: 'localhost'
flaresolverr        |   },
flaresolverr        |   [Symbol(kMessage)]: 'getaddrinfo EAI_AGAIN localhost'
```

**Comment by jeanfrancoislarente** [comment] 2022-02-09 18:50
Perhaps additional details... I can't see the contents of `/etc/resolv.conf` when I jump into the container...

`d run -it ghcr.io/flaresolverr/flaresolverr:latest /bin/sh`

```
/ $ cat /etc/resolv.conf
cat: can't open '/etc/resolv.conf': Permission denied
```

`whoami` says I'm running as the user node. Does that user have the correct permissions?

**Closed** 2022-04-16 18:38 UTC
Labels: more information needed
