### ISSUE TITLE
[YGG] 500 Internal Server Error & Error solving challenge

### ISSUE THREAD

**Issue by Noaaam** [FlareSolverr/FlareSolverr#1244] opened 2024-07-02 09:43 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: 3.3.21
- Operating system: Debian GNU/Linux 12 (bookworm)
- Are you using Docker: YES
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: YES
- Are you using a Proxy: NO
- Are you using Captcha Solver: NO
- If using captcha solver, which one: N/A
- URL to test this issue: YGG.RE
```

### Description

Hello, since yesterday I have a problem with my Flaresolverr, it arrived suddenly without restarting or anything.

My flaresolverr doesn't want to resolve the captcha without knowing why, it's the YGG captcha, maybe there's still a need to make another patch, I don't know.

I've tried setting the language to `fr_FR`, and `en_GB` and `en_US` i have set timeout to `180000` but nothing works!

I checked I have no problem with two of three test indexers: Torrent[CORE], TorrentQQ
For IDOPE the domain must have changed I have this error :
`Exception (idope): Name does not resolve: Name does not resolve (idope.se:443)`

This is my error on Jackett :
`Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.`

### Logged Error Messages

```text
flaresolverr  | 2024-07-02 11:31:54 INFO     FlareSolverr 3.3.21
flaresolverr  | 2024-07-02 11:31:54 INFO     Testing web browser installation...
flaresolverr  | 2024-07-02 11:31:54 INFO     Platform: Linux-6.1.0-22-amd64-x86_64-with-glibc2.31
flaresolverr  | 2024-07-02 11:31:54 INFO     Chrome / Chromium path: /usr/bin/chromium
flaresolverr  | 2024-07-02 11:31:54 INFO     Chrome / Chromium major version: 120
flaresolverr  | 2024-07-02 11:31:54 INFO     Launching web browser...
flaresolverr  | 2024-07-02 11:31:55 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
flaresolverr  | 2024-07-02 11:31:55 INFO     Test successful!
flaresolverr  | 2024-07-02 11:31:55 INFO     Serving on http://0.0.0.0:8191
flaresolverr  | 2024-07-02 11:31:58 INFO     127.0.0.1 GET http://0.0.0.0:8191/ 200 OK
flaresolverr  | 2024-07-02 11:32:31 INFO     Incoming request => POST /v1 body: {'maxTimeout': 90000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?do=search&order=desc&sort=publish_date&category=all'}
flaresolverr  | 2024-07-02 11:32:44 INFO     127.0.0.1 GET http://0.0.0.0:8191/ 200 OK
flaresolverr  | 2024-07-02 11:33:07 INFO     Challenge detected. Selector found: #turnstile-wrapper
flaresolverr  | 2024-07-02 11:33:29 INFO     127.0.0.1 GET http://0.0.0.0:8191/ 200 OK
flaresolverr  | 2024-07-02 11:34:02 ERROR    Error: Error solving the challenge. Timeout after 90.0 seconds.
flaresolverr  | 2024-07-02 11:34:02 INFO     Response in 90.729 s
flaresolverr  | 2024-07-02 11:34:02 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
flaresolverr  | 2024-07-02 11:34:14 INFO     127.0.0.1 GET http://0.0.0.0:8191/ 200 OK
```

**Comment by Kitchigo** [comment] 2024-07-02 13:02
Hi, I have same issue

**Comment by VonKavalier** [comment] 2024-07-02 13:28
Same for me. There might be another patch to make once again :confused: 
(Also thanks for the idea of a test indexer)

**Comment by TayZ3r** [comment] 2024-07-02 13:29
Duplicate of #1036

**Comment by VonKavalier** [comment] 2024-07-02 13:30
What's the best way to report this kind of error without creating duplicates ?

**Comment by TayZ3r** [comment] 2024-07-02 13:32
Well you don't need to report it as it's already being fixed since Jan 12.
Some temporary fixes are sometimes published on #1163

**Comment by sanchobouillant** [comment] 2024-07-02 13:38
Why do we all have the same error only since yesterday if it has been fixed since January?

**Comment by sanchobouillant** [comment] 2024-07-02 14:01
btw the 21hsmw fork doesn't work :)

**Comment by SadE54** [comment] 2024-07-02 15:44
@sanchobouillant : are you're using the nodriver branch and setup accordingly your docker compose ?

**Comment by foxan54** [comment] 2024-07-02 15:59
> @sanchobouillant : are you're using the nodriver branch and setup accordingly your docker compose ?

J’ai le même problème. Je ne suis pas assez doué en Docker, mais hier, j’ai essayé l’image de 21hsmw/flaresolverr en ajoutant la variable “Driver=nodriver”. Cependant, je n’ai rien configuré (je n’avais jamais rien configuré auparavant et cela fonctionnait).

I have the same problem. I’m not skilled enough in Docker, but yesterday, I tried the image from 21hsmw/flaresolverr by adding the variable “Driver=nodriver”. However, I didn’t configure anything (I had never configured anything before and it was working).


`version: '3'
services:
  flaresolverr:
    image: 21hsmw/flaresolverr:nodriver
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
      - Driver=nodriver
    restart: unless-stopped
`

**Comment by sanchobouillant** [comment] 2024-07-02 16:05
Yes, I did. Given the number of people who are struggling with it (myself included), perhaps a small tutorial would be beneficial to avoid this kind of ticket?

**Closed** 2024-07-02 16:17 UTC
