### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Captcha detected but no automatic solver is configured.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Captcha detected but no automatic solver is configured. (Test)

### ISSUE THREAD

**Issue by Eldoc62** [FlareSolverr/FlareSolverr#135] opened 2021-05-29 13:34 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**:
* **Last working FlareSolverr version**:
* **Operating system**:
* **Are you using Docker**: [yes/no]
* **Are you using a proxy or VPN?** [yes/no]
* **Are you using Captcha Solver:** [yes/no]
* **If using captcha solver, which one:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

Bonjour,

Il est question de captcha mais quand on se logue sur l'adresse je n'en voit pas.
Mille merci les gars 👍

**Comment by YggNode** [comment] 2021-05-29 14:26
Si : tu en vois mais sans rentrer dans les détails techniques, il est invisible pour toi mais pas pour flaresolverr...

**Comment by moreje** [comment] 2021-05-29 22:55
La même pour moi...quelle est la solution?

**Comment by hergonoway** [comment] 2021-05-30 01:55
Duplicate of #134

related to new captcha challenges as for issue 134

**Comment by ngosang** [comment] 2021-05-30 11:41
FlareSolverr v1.2.6 will fix this issue. Will be released today.

**Closed** 2021-05-30 11:40 UTC

**Comment by ngosang** [comment] 2021-05-30 13:15
FlareSolverr v1.2.6 released.
