### ISSUE TITLE
Stack Docker with vpn : Error: Error solving the challenge

### ISSUE THREAD

**Issue by Nimothenicefish** [FlareSolverr/FlareSolverr#1302] opened 2024-07-30 10:18 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: -
- Operating system: NAS Synology
- Are you using Docker: yes
- FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: yes
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one: -
- URL to test this issue: http://www.google.com/
```

### Description

Hello, 

I have installed flaresolverr in a docker stack with a vpn on NAS Synology.
When I run this test, I get an error: 

`curl -L -X POST 'http://localhost:8191/v1' -H 'Content-Type : application/json' --data-raw '{
  « cmd « : “ request.get ”,
  «  url « : “ http://www.google.com/ ”,
  « maxTimeout « : 60000
}'`

Response : `{ « status “ : ” error “, ” message “ : ” Erreur : Error solving the challenge. cannot access local variable “driver” where it is not associated with a value “, ” startTimestamp “ : 1722334155585, ” endTimestamp “ : 1722334230120, ” version “ : ” 3.3.21 »}.`

Initially, I want to use flaresolverr with jackett or prowlarr but I get the same error.

Can you help me? 

Thank You !

### Logged Error Messages

```text
2024-07-30 12:09:15 INFO     ReqId 139849302537984 Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'http://www.google.com/', 'maxTimeout': 60000}
2024-07-30 12:09:15 DEBUG    ReqId 139849302537984 Launching web browser...
2024-07-30 12:09:16 DEBUG    ReqId 139849302537984 Started executable: `/app/chromedriver` in a child process with pid: 426
2024-07-30 12:10:30 ERROR    ReqId 139849302537984 Error starting Chrome: Message: unknown error: cannot connect to chrome at 127.0.0.1:46547
from chrome not reachable
Stacktrace:
#0 0x561fce9d0233 <unknown>
#1 0x561fce699e6e <unknown>
#2 0x561fce68821e <unknown>
#3 0x561fce6d242c <unknown>
#4 0x561fce6c9825 <unknown>
#5 0x561fce71c370 <unknown>
#6 0x561fce71b957 <unknown>
#7 0x561fce7111a3 <unknown>
2024-07-30 12:10:30 ERROR    ReqId 139849302537984 Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value
2024-07-30 12:10:30 DEBUG    ReqId 139849302537984 Response => POST /v1 body: {'status': 'error', 'message': "Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value", 'startTimestamp': 1722334155585, 'endTimestamp': 1722334230120, 'version': '3.3.21'}
2024-07-30 12:10:30 INFO     ReqId 139849302537984 Response in 74.535 s
2024-07-30 12:10:30 INFO     ReqId 139849302537984 172.29.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```

### Screenshots

![image](https://github.com/user-attachments/assets/431dd457-3a41-4930-9a7f-0a96f4531ee8)
![image](https://github.com/user-attachments/assets/8a4cbcf9-16c1-4ccf-8e4b-0120d15bdca8)

**Comment by gothdawid** [comment] 2024-07-30 11:03
Duplicate
#1253

**Comment by ewerx** [comment] 2024-07-30 16:36
since we can't comment on #1253 -- any updates? any workarounds?

**Comment by darktemplar242** [comment] 2024-07-30 16:55
> since we can't comment on #1253 -- any updates? any workarounds?

Last similar Issue was closed as not planned, there was a workaround which does not work anymore and no updates on this.

**Comment by HijackHornet** [comment] 2024-07-30 19:39
So at this stage this tool is dead. Lets hope a solution is found but it looks like its going to take a long time..

**Comment by rwarner** [comment] 2024-07-31 20:27
Echoing the same, I just went to try the following as of today on `3.3.21` and still doesn't work for me:

```
- sudo docker exec -u 0 -it flaresolverr /bin/bash
- mv flaresolverr_service.py flaresolverr_service.py_bak
- curl -o flaresolverr_service.py https://raw.githubusercontent.com/MCG-pok/FlareSolverr/master/src/flaresolverr_service.py
- exit
- sudo docker restart flaresolverr
```

**Comment by ilike2burnthing** [comment] 2024-08-01 01:40
This has nothing to do with #1253, but it is a duplicate of a few open issues

**Closed by ilike2burnthing** 2024-08-01 01:40 UTC
