### ISSUE TITLE
proxy not work

### ISSUE THREAD

**Issue by liuzz07** [FlareSolverr/FlareSolverr#1407] opened 2024-11-05 08:16 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: None
- Operating system: macOS Sonoma14.6
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] yes
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue: https://solscan.io/account/7L1HBfMHM6kfieBiqHaosS2R44fGQy8fWCpSHAXarmaH
```

### Description

Step 1. Get cookie using proxy parameter
```
response = requests.post(
    http://localhost:8191/v1,
    headers={'Content-Type': 'application/json'},
    data={'cmd': 'request.get', 'url': 'https://solscan.io/account/7L1HBfMHM6kfieBiqHaosS2R44fGQy8fWCpSHAXarmaH', 'maxTimeout': 120000, 'proxy': {'url': 'http://10.103.11.159:3128'}}
)

print(response.status_code)  # 200
```

Step 2. Request with cookie and same proxy ip
```
resp = requests.get(
    "https://api-v2.solscan.io/v2/account/stake?address=7L1HBfMHM6kfieBiqHaosS2R44fGQy8fWCpSHAXarmaH&limit=20&page=1", 
    headers=headers, 
    cookies=cookies,
    proxies={'http': 'http://10.103.11.159:3128', 'https': 'http://10.103.11.159:3128'}
)
print(resp.status_code)  # 403
```
block by cloudflare, sames proxy not work, and if not use proxy in step 1 and step 2, it works, anyone can help me, many thx

### Logged Error Messages

```text
2024-11-05 08:14:39 DEBUG    ReqId 281473588396512 Cloudflare verify checkbox not found on the page.
2024-11-05 08:14:39 DEBUG    ReqId 281473588396512 Try to find the Cloudflare 'Verify you are human' button...
2024-11-05 08:14:39 DEBUG    ReqId 281473588396512 The Cloudflare 'Verify you are human' button not found on the page.
2024-11-05 08:14:41 DEBUG    ReqId 281473588396512 Waiting for title (attempt 62): Just a moment...
2024-11-05 08:14:42 DEBUG    ReqId 281473588396512 Timeout waiting for selector
2024-11-05 08:14:42 DEBUG    ReqId 281473588396512 Try to find the Cloudflare verify checkbox...
2024-11-05 08:14:42 DEBUG    ReqId 281473588396512 Cloudflare verify checkbox not found on the page.
2024-11-05 08:14:42 DEBUG    ReqId 281473588396512 Try to find the Cloudflare 'Verify you are human' button...
2024-11-05 08:14:42 DEBUG    ReqId 281473588396512 The Cloudflare 'Verify you are human' button not found on the page.
2024-11-05 08:14:44 DEBUG    ReqId 281473588396512 Waiting for title (attempt 63): Just a moment...
2024-11-05 08:14:45 DEBUG    ReqId 281473588396512 Timeout waiting for selector
2024-11-05 08:14:45 DEBUG    ReqId 281473588396512 Try to find the Cloudflare verify checkbox...
2024-11-05 08:14:45 DEBUG    ReqId 281473588396512 Cloudflare verify checkbox not found on the page.
2024-11-05 08:14:45 DEBUG    ReqId 281473588396512 Try to find the Cloudflare 'Verify you are human' button...
2024-11-05 08:14:45 DEBUG    ReqId 281473588396512 The Cloudflare 'Verify you are human' button not found on the page.
2024-11-05 08:14:47 DEBUG    ReqId 281473588396512 Waiting for title (attempt 64): Just a moment...
2024-11-05 08:14:48 DEBUG    ReqId 281473588396512 Timeout waiting for selector
2024-11-05 08:14:48 DEBUG    ReqId 281473588396512 Try to find the Cloudflare verify checkbox...
2024-11-05 08:14:48 DEBUG    ReqId 281473588396512 Cloudflare verify checkbox not found on the page.
2024-11-05 08:14:48 DEBUG    ReqId 281473588396512 Try to find the Cloudflare 'Verify you are human' button...
2024-11-05 08:14:48 DEBUG    ReqId 281473588396512 The Cloudflare 'Verify you are human' button not found on the page.
2024-11-05 08:14:50 DEBUG    ReqId 281473588396512 Waiting for title (attempt 65): Just a moment...
2024-11-05 08:14:51 DEBUG    ReqId 281473588396512 Timeout waiting for selector
2024-11-05 08:14:51 DEBUG    ReqId 281473588396512 Try to find the Cloudflare verify checkbox...
2024-11-05 08:14:51 DEBUG    ReqId 281473588396512 Cloudflare verify checkbox not found on the page.
2024-11-05 08:14:51 DEBUG    ReqId 281473588396512 Try to find the Cloudflare 'Verify you are human' button...
2024-11-05 08:14:51 DEBUG    ReqId 281473588396512 The Cloudflare 'Verify you are human' button not found on the page.
2024-11-05 08:14:53 DEBUG    ReqId 281473588396512 Waiting for title (attempt 66): Just a moment...
2024-11-05 08:14:54 DEBUG    ReqId 281473588396512 Timeout waiting for selector
2024-11-05 08:14:54 DEBUG    ReqId 281473588396512 Try to find the Cloudflare verify checkbox...
2024-11-05 08:14:54 DEBUG    ReqId 281473588396512 Cloudflare verify checkbox not found on the page.
2024-11-05 08:14:54 DEBUG    ReqId 281473588396512 Try to find the Cloudflare 'Verify you are human' button...
2024-11-05 08:14:54 DEBUG    ReqId 281473588396512 The Cloudflare 'Verify you are human' button not found on the page.
2024-11-05 08:14:56 DEBUG    ReqId 281473588396512 Waiting for title (attempt 67): Just a moment...
```

**Comment by ilike2burnthing** [comment] 2024-12-11 10:30
If the issue is just that use of a proxy causes Cloudflare protection to be triggered, then you need to change the proxy being used, or not use one at all. See pinned issues and recent PRs for why FlareSolverr isn't resolving the challenge.

**Closed as completed by ilike2burnthing** 2024-12-11 10:30 UTC
