### ISSUE TITLE
error: Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by jprokos** [FlareSolverr/FlareSolverr#219] opened 2021-11-12 20:30 UTC
### Discussed in https://github.com/FlareSolverr/FlareSolverr/discussions/218

<div type='discussions-op-text'>

<sup>Originally posted by **jprokos** November 10, 2021</sup>
FlareSolverr 2.0.2 was working and now it's not. I haven't changed anything on my system. I have SIP off, no firewall, and no security software running.

```
2021-11-05T00:23:25-05:00 INFO REQ-134 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://kickasstorrents.unblockninja.com/new/?sortby=time&sort=desc"}
2021-11-05T00:23:27-05:00 INFO REQ-134 Cloudflare detected
2021-11-05T00:23:36-05:00 INFO REQ-134 Challenge solved
2021-11-05T00:23:38-05:00 INFO REQ-134 Response in 12.777 s
2021-11-05T00:29:37-05:00 INFO REQ-134 Process interrupted
2021-11-05T00:39:15-05:00 INFO FlareSolverr v2.0.2
2021-11-05T00:39:15-05:00 INFO Testing web browser installation...
2021-11-05T03:02:50-05:00 INFO FlareSolverr v2.0.2
2021-11-05T03:02:50-05:00 INFO Testing web browser installation...
2021-11-05T16:07:46-05:00 INFO FlareSolverr v2.0.2
2021-11-05T16:07:46-05:00 INFO Testing web browser installation...
2021-11-05T21:59:10-05:00 INFO FlareSolverr v2.0.2
2021-11-05T21:59:10-05:00 INFO Testing web browser installation...
2021-11-06T14:05:01-05:00 INFO FlareSolverr v2.0.2
2021-11-06T14:05:01-05:00 INFO Testing web browser installation...
2021-11-06T22:30:13-05:00 INFO FlareSolverr v2.0.2
2021-11-06T22:30:13-05:00 INFO Testing web browser installation...
2021-11-06T22:30:56-05:00 INFO FlareSolverr v2.0.2
2021-11-06T22:30:56-05:00 INFO Testing web browser installation...
2021-11-06T22:31:04-05:00 INFO FlareSolverr v2.0.2
2021-11-06T22:31:04-05:00 INFO Testing web browser installation...
2021-11-06T22:34:13-05:00 INFO FlareSolverr v2.0.2
2021-11-06T22:34:13-05:00 INFO Testing web browser installation...
2021-11-06T22:41:05-05:00 INFO FlareSolverr v2.0.2
2021-11-06T22:41:05-05:00 INFO Testing web browser installation...
2021-11-06T22:51:35-05:00 INFO FlareSolverr v2.0.2
2021-11-06T22:51:35-05:00 INFO Testing web browser installation...
2021-11-06T22:51:40-05:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0
2021-11-06T22:51:40-05:00 INFO Test successful
2021-11-06T22:51:40-05:00 INFO Listening on http://0.0.0.0:8191
2021-11-06T22:51:43-05:00 INFO REQ-1 Incoming request => GET /
2021-11-06T22:51:43-05:00 INFO REQ-2 Incoming request => GET /favicon.ico
2021-11-06T22:53:09-05:00 INFO REQ-3 Incoming request => GET /
2021-11-06T22:56:19-05:00 INFO REQ-4 Incoming request => GET /
2021-11-07T00:04:24-05:00 INFO REQ-5 Incoming request => GET /
2021-11-07T00:04:24-05:00 INFO REQ-6 Incoming request => GET /favicon.ico
2021-11-09T00:03:01-06:00 INFO REQ-6 Process interrupted
2021-11-09T00:04:21-06:00 INFO FlareSolverr v2.0.2
2021-11-09T00:04:21-06:00 INFO Testing web browser installation...
2021-11-09T10:20:14-06:00 INFO FlareSolverr v2.0.2
2021-11-09T10:20:14-06:00 INFO Testing web browser installation...
2021-11-09T10:20:25-06:00 INFO FlareSolverr v2.0.2
2021-11-09T10:20:25-06:00 INFO Testing web browser installation...
2021-11-09T10:20:35-06:00 INFO FlareSolverr v2.0.2
...
```
Error log
```}
2021-11-10T21:21:50-06:00 ERROR ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://localhost:63361/devtools/browser/4b8de2bc-fe9b-4944-9884-692cb96ee0e1',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'connect ECONNREFUSED ::1:63361',
  error: Error: connect ECONNREFUSED ::1:63361
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 63361
  }
}```</div>

**Comment by ngosang** [comment] 2021-11-21 19:06
* Are you using Proxy?
* Why FlareSolverr is restarting every few hours?
* What are the resources (CPU / RAM) of your server?

**Comment by jprokos** [comment] 2021-11-22 18:56
Hi,

No proxy but I am connected to a VPN once in awhile - this wasn't an issue in the past that I know of.

Some of those lines are me attempting to run it manually using `npm start` over and over after turning off the launch service I created and testing different environmental flags

I am using this in Jackett, so whenever Jackett requires it I guess there is a line stating that it has failed?

I am using a launch agent on mac. It was working flawlessly for the 1.x version.

**Comment by devIlluSioN** [comment] 2021-12-02 12:43
Hello
No other solution other than installing docker? I would like to do without that :)

**Comment by jprokos** [comment] 2021-12-07 03:28
@ngosang 

I answered the questions you asked. Is there something else I can look for to resolve this?

**Comment by ngosang** [comment] 2021-12-12 16:17
FlareSolverr 1.x.x was working in MacOS but I'm not sure about the 2.x.x branch. I don't have the hardware to test it. If you have followed the install instructions for Linux and it's not working maybe there is no fix.
You can ask for help here => https://github.com/FlareSolverr/FlareSolverr/discussions/99

**Comment by jprokos** [comment] 2021-12-12 21:40
@ngosang 

I wish this were true... It is working randomly and I haven't been able to pin down why this is happening. Once it's able to get a port it works. It was running for three days straight. For some reason it's not always able to get a port. I have checked to see if there are port conflicts and I see none. So it must be in the way it is requesting them that it's hit and miss.

**Comment by ngosang** [comment] 2022-01-30 23:49
FlareSolverr 2.2.0 is released with relevant changes.

**Closed** 2022-02-06 10:16 UTC
Labels: more information needed

**Comment by alexreg** [comment] 2022-03-23 16:55
v2.2 is still not working for me on macOS.

**Comment by jprokos** [comment] 2022-04-04 18:19
> v2.2 is still not working for me on macOS.

@alexreg It's working for me on macOS Catalina. Make sure you are building it using nodeJS 16. Make sure you are running it using the same. You can also use the launch.plist on macOS.

**Comment by alexreg** [comment] 2022-04-04 20:11
@jprokos Thanks, but it's still not working for me. Could be because I'm on a newer version of macOS (12.3.1). I'm using Node 17.8.0 and NPM 8.6.0, so I doubt that's the problem. The issue is most likely compatibility with different versions of macOS, or simply the flakiness of Pupeteer's support for Firefox.

@ngosang Did you see my above comment? And is there any recent FlareSolverr uses Puppeteer's unstable support for Firefox rather than the stable support for Chromium?

**Comment by jprokos** [comment] 2022-04-04 20:19
> @jprokos Thanks, but it's still not working for me. Could be because I'm on a newer version of macOS (12.3.1). I'm using Node 17.8.0 and NPM 8.6.0, so I doubt that's the problem. The issue is most likely compatibility with different versions of macOS, or simply the flakiness of Pupeteer's support for Firefox.
> 
> @ngosang Did you see my above comment? And is there any recent FlareSolverr uses Puppeteer's unstable support for Firefox rather than the stable support for Chromium?

I wrote that you have to use node 16 not the latest version. That is your issue.

**Comment by alexreg** [comment] 2022-04-04 21:18
@jprokos Oh, sorry. I had interpreted that as "Node 16 or later"; my mistake. Indeed, it works with Node 16... thank you!

Is Node 17 compatibility in the works, incidentally?

**Comment by jprokos** [comment] 2022-04-04 22:59
> @jprokos Oh, sorry. I had interpreted that as "Node 16 or later"; my mistake. Indeed, it works with Node 16... thank you!
> 
> 
> 
> Is Node 17 compatibility in the works, incidentally?

I am not involved in writing. Just a lot of troubleshooting getting it installed on macOS. Glad you have it working

**Comment by alexreg** [comment] 2022-04-04 23:35
@jprokos Yeah, that question was directed at the maintainers like @ngosang really. In any case, appreciate your advice.

**Comment by ngosang** [comment] 2022-04-16 17:34
@alexreg I can reproduce the issue with NodeJS 17 but it's related to Puppeter/Firefox not FlareSolverr. For now I will support only NodejS 16 LTS. You can install that version or use the Docker container.

**Comment by jprokos** [comment] 2022-04-16 17:40
Have you considered playright vs puppeteer? Seems to be well maintained and have fewer conflicts.

**Comment by alexreg** [comment] 2022-04-16 17:43
Sounds fair enough, thanks.

**Comment by ngosang** [comment] 2022-04-16 18:57
> Have you considered playwright vs puppeteer? Seems to be well maintained and have fewer conflicts.

#365
