### ISSUE TITLE
ERROR TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by GOLDENLULUZ** [FlareSolverr/FlareSolverr#238] opened 2021-12-07 03:42 UTC
FlareSolverr version:latest
Operating system:
Are you using Docker: yes
Are you using a proxy or VPN?: no
Are you using Captcha Solver: no

### Description

hello, I am trying to set up FlareSolverr on a qnap nas, so I didn't really know the system version. I just copied the docker compose to creat the docker, but Jackett didn't work as expected ("Error connecting to FlareSolverr server"), and I saw some error in the log of FlareSolverr. Could you help me to solve the problem? Thank you.

### Logged Error Messages
2021-12-07T03:20:16+00:00 INFO Testing web browser installation...
2021-12-07T03:21:07+00:00 ERROR TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/node/flaresolverr/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111
    at async FrameManager.navigateFrame (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:70:21)
    at async Frame.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:295:16)
    at async Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:16)
    at async testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:56:5)
  -- ASYNC --
    at Frame.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:53)
    at Page.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:95:27)
    at testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:56:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by GOLDENLULUZ** [comment] 2021-12-07 09:06
does google involve in the setup of FlareSolverr? I think it might be caused by the internet block.

**Comment by ilike2burnthing** [comment] 2021-12-07 20:11
As per https://github.com/FlareSolverr/FlareSolverr/issues/202, you may need to increase the [browser timeout](https://github.com/FlareSolverr/FlareSolverr#environment-variables) and/or free up some resources.

`latest` isn't a version, but if you've only recently pulled the `:latest` image then it's v2.0.2 - you can confirm this in browser by checking the local IP address of the device FlareSolverr is running on and the port used by FlareSolverr, e.g. http://192.168.0.2:8191 (what are you using in Jackett?)

A connection to google.com is checked at startup to confirm the browser is working. Is that site blocked for you?

**Comment by GOLDENLULUZ** [comment] 2021-12-08 01:23
Thank you ilike2burnthing. I just found out that I don't really need FlareSolverr to support the sites I need in Jackett, so I think I will leave the problem behind instead of learning how to use proxy in docker.

And yes, google and many sites are blocked in my place, so if you are interested, maybe you could try improve FlareSolverr by giving a proxy option or something, like in Jackett.

**Comment by ilike2burnthing** [comment] 2021-12-08 01:37
@ngosang another case for making the test URL configurable - ref https://github.com/FlareSolverr/FlareSolverr/issues/224#issuecomment-974876210

**Comment by ngosang** [comment] 2021-12-08 19:27
I don't know if this is the cause but I will make the test URl configurable in #240
Closing for now

**Closed by ngosang** 2021-12-08 19:27 UTC
