### ISSUE TITLE
Challenge solved, but Prowlarr reports blocked

### ISSUE THREAD

**Issue by lielianjie** [FlareSolverr/FlareSolverr#1139] opened 2024-04-02 11:17 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.16
- Last working FlareSolverr version: 3.3.16 (I guess)
- Operating system: Synology
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://www3.yggtorrent.qa
```

### Description

Hi, 

Since few days I have this issue with YGG (see logs). 
It seems that the challenge is solved but I have a timeout. 
I'm using Prowlarr since a while and never had this issue before. 

### Logged Error Messages

```text
2024-04-02 10:59:17 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
version_main cannot be converted to an integer
2024-04-02 10:59:21 INFO     Challenge detected. Title found: Just a moment...
2024-04-02 10:59:26 INFO     Challenge solved!
2024-04-02 10:59:26 INFO     Response in 9.096 s
2024-04-02 10:59:26 INFO     192.168.1.102 POST http://192.168.1.103:8191/v1 200 OK
```

**Comment by K3RM1T-CYBER** [comment] 2024-04-02 17:26
Same

**Comment by daniwalter001** [comment] 2024-04-02 17:46
Same

**Comment by KATTIX** [comment] 2024-04-02 17:58
same here

**Comment by ilike2burnthing** [comment] 2024-04-02 19:48
@KATTIX https://github.com/FlareSolverr/FlareSolverr/issues/1036

@lielianjie where are you seeing a timeout?

**Comment by lielianjie** [comment] 2024-04-02 20:47
> @KATTIX #1036
> 
> @lielianjie where are you seeing a timeout?

I guess I thought it was a timeout issue because I saw "maxTimeout': 60000" but in Prowlarr, I have this error:
![image](https://github.com/FlareSolverr/FlareSolverr/assets/13405364/4a3d0b7c-fef4-4d5f-9211-e1e50da85a4a)

and in Flaresolverr logs, I have this error: 

2024-04-02 10:59:17 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
version_main cannot be converted to an integer

**Comment by ilike2burnthing** [comment] 2024-04-03 00:39
Follow the troubleshooting steps here -https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

Is Prowlarr installed natively or also in Docker?

**Comment by lielianjie** [comment] 2024-04-03 07:53
Prowlarr is also installed on docker but on another Synology. 
I just read in your troubleshooting that both Flaresolverr and Prowlarr should be isntall on the same host so I'll do that and I'll check the rest of the troubleshooting and I'll get back to you.
Odd though because everything was working flawlessly during many months.

**Comment by K3RM1T-CYBER** [comment] 2024-04-03 09:38
I was in the same situation as him. I just moved my prowlarr container to the same server as my flaresolverr, it seems to be working again. THANKS :)

**Comment by Guesh1337** [comment] 2024-04-03 13:07
I'm using Jackett and Flaresolverr on the same linux machine using docker and i'm having this issue since 3 days on YGG

**Comment by Brokeos** [comment] 2024-04-03 17:23
Running on docker, without vpn / proxy

> 
2024-04-03 17:19:24 DEBUG    ReqId 140383032174336 Navigating to... https://www3.yggtorrent.qa/engine/search?do=search&order=desc&sort=publish_date&category=all
2024-04-03 17:19:24 INFO     ReqId 140383032174336 Challenge detected. Title found: Just a moment...
2024-04-03 17:19:24 DEBUG    ReqId 140383032174336 Waiting for title (attempt 1): Just a moment...
2024-04-03 17:19:25 DEBUG    ReqId 140383032174336 Timeout waiting for selector
2024-04-03 17:19:25 DEBUG    ReqId 140383032174336 Try to find the Cloudflare verify checkbox...
2024-04-03 17:19:25 DEBUG    ReqId 140383032174336 Cloudflare verify checkbox not found on the page.
2024-04-03 17:19:25 DEBUG    ReqId 140383032174336 Try to find the Cloudflare 'Verify you are human' button...
2024-04-03 17:19:25 DEBUG    ReqId 140383032174336 The Cloudflare 'Verify you are human' button not found on the page.
...
2024-04-03 17:20:19 DEBUG    ReqId 140383032174336 Waiting for title (attempt 18): Just a moment...
2024-04-03 17:20:19 DEBUG    ReqId 140383065745152 A used instance of webdriver has been destroyed
2024-04-03 17:20:19 ERROR    ReqId 140383065745152 Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-04-03 17:20:19 DEBUG    ReqId 140383065745152 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 55.0 seconds.', 'startTimestamp': 1712164764113, 'endTimestamp': 1712164819840, 'version': '3.3.12'}

**Comment by Brokeos** [comment] 2024-04-03 17:27
I just installed on a debian VM, works perfectly, maybe a problem with the docker image?

**Comment by ilike2burnthing** [comment] 2024-04-03 17:31
See troubleshooting and issue linked above.

**Comment by lielianjie** [comment] 2024-04-03 17:38
> Follow the troubleshooting steps here -https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting
> 
> Is Prowlarr installed natively or also in Docker?

So I followed the troubleshooting guide but unfortunately it's still not good.

In Prowlarr : 
![image](https://github.com/FlareSolverr/FlareSolverr/assets/13405364/9d6cc6dc-84b9-4163-9db9-57eb751e56e8)

In Flaresolverr logs: 

2024-04-03 17:35:54 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
version_main cannot be converted to an integer
2024-04-03 17:36:02 INFO     Challenge detected. Title found: Just a moment...
2024-04-03 17:36:06 INFO     Challenge solved!
2024-04-03 17:36:07 INFO     Response in 12.216 s
2024-04-03 17:36:07 INFO     192.168.1.102 POST http://192.168.1.102:8191/v1 200 OK

**Comment by LightSeek3r** [comment] 2024-04-04 03:57
I have the same issue since a few days on native windows install (both Prowlarr and Flaresolverr are installed natively). It used to be working fine for quite some time, until now.

**Comment by ilike2burnthing** [comment] 2024-04-04 04:00
Answer the questions from https://github.com/FlareSolverr/FlareSolverr/issues/1139#issuecomment-2035221857.

**Comment by LightSeek3r** [comment] 2024-04-04 04:44
So to be clear, they are both running on the same device, not on docker as I said they are both running natively on Windows (11), there is no VPN involved and IPV6 is disabled. Confirmed.

As previously mentionned, this untouched setup (system & softwares) used to work for months. As you can see from the other comments, it's not a one user issue. Wild guess here, it is most likely an issue between Flaresolverr, Cloudfare, and YGG. Specifically. Knowing how YGG admins can be a pain and somehow stubborn and off logic, I'd say maybe they changed something in their Cloudfare config. But I'm not an expert in Cloudfare, nor networking in general.

I'm not using iDope but qBittorrent which is otherwise working perfectly, why would I use Mac Torrents on Windows, and is there a specific reason why I would have to use a specific torrent client such as torrent core instead of qBittorrent?

Thanks for your helping and relevancy.

**Comment by ilike2burnthing** [comment] 2024-04-04 04:48
Those are indexers in Jackett and Prowlarr, not torrent clients. Add and test them.

**Comment by LightSeek3r** [comment] 2024-04-04 05:18
So, iDope and Torrent[CORE] fail the same way as YggTorrents does, the challenge is not resolved. Mac Torrents test passes. 
![Screenshot_2024-04-04-14-13-08-677_net dwservice client-edit](https://github.com/FlareSolverr/FlareSolverr/assets/75648597/9c80587b-3cb5-4248-ab6d-fe01698ae35b)

**Comment by ilike2burnthing** [comment] 2024-04-04 05:25
Oh, looks like Mac Torrents Download has dropped the Cloudflare challenge. Try Cinecalidad instead. Also try increasing the FlareSolverr timeout to 120s.

**Comment by cahuete95** [comment] 2024-04-04 21:35
@lielianjie activate debug log in flaresolver and you might have the same logs than in https://github.com/FlareSolverr/FlareSolverr/issues/1113#issuecomment-1988167935

@ilike2burnthing i think it's the same concern than the behaviour in the issue mentionned : infinite loop on cloudflare challenge for ygg.
ygg only it seems because i didn't notice the same on other sites using/needing flaresolver (i've have a few and i'm with prowlarr too)

**Comment by super-upup** [comment] 2024-04-05 02:22
Same timeout problem,i had try 120s.
The quizzer's `https://www3.yggtorrent.qa/engine/search?category=all&do=search&order=desc&sort=publish_date` is OK.
Can someone help me try this website `https://xslist.org/zh/searchByImage/` work?

**Comment by lielianjie** [comment] 2024-04-05 16:39
> > Well, I did try everything you guys asked here but nothing worked. No VPN, no proxy, no IPV6. Both Prowlarr and Flare on the same host and docker. Timeout at 120s in Prowlarr.
> 
> try another computer,the web you curl can work on FlareSolverr

What do you mean? Is it working for you? 
I have my whole infrastructure installed on a server, I can't just migrate everything from on another computer just for testing.

**Comment by lielianjie** [comment] 2024-04-05 16:53
[_flaresolverr_logs.txt](https://github.com/FlareSolverr/FlareSolverr/files/14888042/_flaresolverr_logs.txt)
Here I tried again with the debug logs.

**Comment by ilike2burnthing** [comment] 2024-04-05 22:11
Remove the indexer from Prowlarr, restart the FlareSolverr and Prowlarr containers, add the indexer again, ensuring to add the tag for FlareSolverr. See if that works.

If not, try the YGGcookie indexer.

As a test you can also try adding a Jackett container, configuring FlareSolverr there, increasing the timeout, and seeing if YGGtorrent works in it.

**Comment by ilike2burnthing** [comment] 2024-04-06 08:10
Haven't checked, but look at https://github.com/FlareSolverr/FlareSolverr/issues/1036.

**Comment by lielianjie** [comment] 2024-04-06 09:36
So I tried with Jackett and I have this error:
![image](https://github.com/FlareSolverr/FlareSolverr/assets/13405364/aad0d96a-ca99-4278-ad70-4427ab147beb)
![image](https://github.com/FlareSolverr/FlareSolverr/assets/13405364/61ba4df1-f036-4108-aceb-c7a285fa7d1e)

Any idea?

**Comment by ilike2burnthing** [comment] 2024-04-06 10:08
Increase the timeout, try with YGGtorrent, not YGGcookie.

**Comment by lielianjie** [comment] 2024-04-06 10:23
Timeout set to 120s.
Challenge solved with both YGGcookie and YGGtorrent:
![image](https://github.com/FlareSolverr/FlareSolverr/assets/13405364/8228f0e2-e42e-456b-ae9c-7b5a5c29cc66)

![image](https://github.com/FlareSolverr/FlareSolverr/assets/13405364/7f25e80e-f043-408b-bb9c-8af53ceddeca)

**Comment by ilike2burnthing** [comment] 2024-04-06 11:03
Both the FlareSolverr and Jackett containers are using the `host` network setting?

How have you disabled IPv6? If per container, did you also disable it for Jackett?

**Comment by lielianjie** [comment] 2024-04-06 15:14
OMG
<img width="857" alt="image" src="https://github.com/FlareSolverr/FlareSolverr/assets/13405364/e5c56f42-6119-4528-97e8-c80418578f1f">

I forgot to change Jackett to host (it was on bridge).
Seems to work with jackett now.

I'll try some real tests.

**Comment by lielianjie** [comment] 2024-04-08 10:37
So finaly, it's working well on Jackett but still not working on Prowlarr after everything i've done. 
It's kinda fine for me but I don't know if you need to keep this issue open or not knowing there is a potential problem with Prowlarr. 
If you want, I can do more tests. 
Anyway, thanks for helped me.

**Comment by V1ck3s** [comment] 2024-04-08 10:59
> So finaly, it's working well on Jackett but still not working on Prowlarr after everything i've done. 
> It's kinda fine for me but I don't know if you need to keep this issue open or not knowing there is a potential problem with Prowlarr. 
> If you want, I can do more tests. 
> Anyway, thanks for helped me.

What's all the steps you've made to fix this on jackett ?

**Comment by lielianjie** [comment] 2024-04-08 12:34
> > So finaly, it's working well on Jackett but still not working on Prowlarr after everything i've done.
> > It's kinda fine for me but I don't know if you need to keep this issue open or not knowing there is a potential problem with Prowlarr.
> > If you want, I can do more tests.
> > Anyway, thanks for helped me.
> 
> What's all the steps you've made to fix this on jackett ?

I didn't used Jackett at all at the beguining so I installed it via Docker on the same server as Flare and at first it didn't worked. 
I realized that the the network setting for the Jackett's container wasn't set to Host but to Bridge. 
I changed it to Host and it worked. 

That beeing said, Prowlarr is correctly configured but it's still doesn't work.

**Comment by V1ck3s** [comment] 2024-04-08 12:59
Ok. I use Jackett on an ARM server, it doesn't work anymore on it.
I installed it on my PC with docker and it works. Don't know why it works on one and not on another. I'll try changing the network to home tonight.

**Comment by ilike2burnthing** [comment] 2024-04-08 15:19
@lielianjie with the YGGtorrent indexer (NOT YGGcookie) you removed the indexer from Prowlarr, restarted the FlareSolverr and Prowlarr containers, added the indexer again, ensuring to add the tag for FlareSolverr, and that didn't change anything?

If not, how have you disabled IPv6?

@V1ck3s see the discussion above and the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

**Comment by lielianjie** [comment] 2024-04-08 15:58
> @lielianjie with the YGGtorrent indexer (NOT YGGcookie) you removed the indexer from Prowlarr, restarted the FlareSolverr and Prowlarr containers, added the indexer again, ensuring to add the tag for FlareSolverr, and that didn't change anything?
> 
> If not, how have you disabled IPv6?
> 
> @V1ck3s see the discussion above and the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

When trying to configure YGGtorrent on Prowlarr, I can't even validate the indexer configuration. 
It give me that error with or without Flare:
![image](https://github.com/FlareSolverr/FlareSolverr/assets/13405364/3d6159f8-8717-41b0-8356-56a3d37d2487)

**Comment by ilike2burnthing** [comment] 2024-04-08 16:04
> how have you disabled IPv6?

**Comment by lielianjie** [comment] 2024-04-08 17:59
> > how have you disabled IPv6?

TBH I don't remember how (certainly did a long time ago) but it is disabled:
![image](https://github.com/FlareSolverr/FlareSolverr/assets/13405364/df3e5454-f2f9-40d0-bc4f-eda2bf10176a)

**Comment by ilike2burnthing** [comment] 2024-04-08 18:23
I'm not familiar with Synology, but as far as I can tell that is their Docker manager app. Try disabling IPv6 for all network interfaces in their control panel instead.

**Comment by lielianjie** [comment] 2024-04-09 09:25
> I'm not familiar with Synology, but as far as I can tell that is their Docker manager app. Try disabling IPv6 for all network interfaces in their control panel instead.

Indeed. In my Syno's network interface, IPV6 is disable and since the network selected for the container is "host" this is why IPV6 is disable for the container as well.

**Comment by ilike2burnthing** [comment] 2024-04-09 09:34
So do `iDope`, `Cinecalidad` and `Torrent[CORE]` now all work in Jackett but all fail in Prowlarr, despite being successful in FlareSolverr?

**Comment by lielianjie** [comment] 2024-04-11 11:56
> So do `iDope`, ~`Cinecalidad`~ and `Torrent[CORE]` now all work in Jackett but all fail in Prowlarr, despite being successful in FlareSolverr?
> 
> Edit: just realised Cinecalidad isn't available in Prowlarr.

Yes, they all work under Jackett.

**Comment by ilike2burnthing** [comment] 2024-04-11 12:04
> but all fail in Prowlarr, despite being successful in FlareSolverr?

**Comment by n1nj444** [comment] 2024-04-11 17:07
Got this on my side : 

-- | -- | --
2024/04/11 19:06:16 | stdout | 2024-04-11 17:06:16 INFO     Challenge detected. Title found: Just a moment...
2024/04/11 19:06:02 | stdout | version_main cannot be converted to an integer
2024/04/11 19:06:02 | stdout | 2024-04-11 17:06:02 INFO     Incoming request => POST /v1 body: {'maxTimeout': 120000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/'}
2024/04/11 19:06:02 | stdout | 2024-04-11 17:06:02 INFO     172.17.0.1 POST http://192.168.1.18:8191/v1 500 Internal Server Error
2024/04/11 19:06:02 | stdout | 2024-04-11 17:06:02 INFO     Response in 121.518 s
2024/04/11 19:06:02 | stdout | 2024-04-11 17:06:02 ERROR    Error: Error solving the challenge. Timeout after 120.0 seconds.
2024/04/11 19:04:14 | stdout | 2024-04-11 17:04:14 INFO     Challenge detected. Title found: Just a moment...

**Comment by Greg1077** [comment] 2024-04-11 20:38
Hey, I think I have the same issue, hope it's ok to share here. 

I've read the troubleshooting, disabled IPv6, moved containers to the same host interface, removed the indexer and restarted, increased time out... 

I'm only using Prowlarr, not Jacket, and Flaresolver stopped working a couple of weeks ago (no VPN, no proxy, same device). 

<img width="664" alt="Screenshot" src="https://github.com/FlareSolverr/FlareSolverr/assets/166755036/f8dc4f11-c421-4760-b54d-a1a9f19ca7fd">

Here are the logs, same outcome with iDope and YGG: 

`2024/04/11 22:32:16	stdout	2024-04-11 20:32:16 INFO     192.168.178.100 POST http://192.168.178.100:8191/v1 500 Internal Server Error
2024/04/11 22:32:16	stdout	2024-04-11 20:32:16 INFO     Response in 181.083 s
2024/04/11 22:32:16	stdout	2024-04-11 20:32:16 ERROR    Error: Error solving the challenge. Timeout after 180.0 seconds.
2024/04/11 22:29:17	stdout	2024-04-11 20:29:17 INFO     Challenge detected. Title found: Just a moment...
2024/04/11 22:29:15	stdout	version_main cannot be converted to an integer
2024/04/11 22:29:15	stdout	2024-04-11 20:29:15 INFO     Incoming request => POST /v1 body: {'maxTimeout': 180000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024/04/11 22:28:27	stdout	2024-04-11 20:28:27 INFO     192.168.178.100 POST http://192.168.178.100:8191/v1 500 Internal Server Error
2024/04/11 22:28:27	stdout	2024-04-11 20:28:27 INFO     Response in 180.987 s
2024/04/11 22:28:27	stdout	2024-04-11 20:28:27 ERROR    Error: Error solving the challenge. Timeout after 180.0 seconds.
2024/04/11 22:25:37	stdout	2024-04-11 20:25:37 INFO     Challenge detected. Title found: Just a moment...
2024/04/11 22:25:26	stdout	version_main cannot be converted to an integer
2024/04/11 22:25:26	stdout	2024-04-11 20:25:26 INFO     Incoming request => POST /v1 body: {'maxTimeout': 180000, 'cmd': 'request.get', 'url': 'https://idope.se/browse.html', 'proxy': {}}
2024/04/11 22:24:56	stdout	2024-04-11 20:24:56 INFO     Serving on http://0.0.0.0:8191
2024/04/11 22:24:56	stdout	2024-04-11 20:24:56 INFO     Test successful!
2024/04/11 22:24:56	stdout	2024-04-11 20:24:56 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024/04/11 22:24:55	stdout	version_main cannot be converted to an integer
2024/04/11 22:24:55	stdout	2024-04-11 20:24:55 INFO     Launching web browser...
2024/04/11 22:24:55	stdout	2024-04-11 20:24:55 INFO     Chrome / Chromium major version: 120
2024/04/11 22:24:55	stdout	2024-04-11 20:24:55 INFO     Chrome / Chromium path: /usr/bin/chromium
2024/04/11 22:24:55	stdout	2024-04-11 20:24:55 INFO     Platform: Linux-4.4.302+-x86_64-with-glibc2.31
2024/04/11 22:24:55	stdout	2024-04-11 20:24:55 INFO     Testing web browser installation...
2024/04/11 22:24:55	stdout	2024-04-11 20:24:55 INFO     FlareSolverr 3.3.13`

**Comment by ilike2burnthing** [comment] 2024-04-11 22:31
As posted several times now - https://github.com/FlareSolverr/FlareSolverr/issues/1036 (i.e. the pinned issue).

**Comment by LightSeek3r** [comment] 2024-04-12 12:11
So, to me all indexers ended up being resolved with the latest update of FlareSolverr, with Prowlarr. But for some reason with YGG via Radarr/Sonarr, I always got "invalid torrent specified" "getting release from indexer failed". Switching from Prowlarr to Jackett solved it once and for all. Confirming there is currently an issue between FlareSolverr & Prowlarr.

**Comment by n1nj444** [comment] 2024-04-12 22:17
> As posted several times now - #1036 (i.e. the pinned issue).

Hey, I actually checked the affected issues before, including the one you just sent. In that one, you recommend increasing the timeout and changing the language. My current configuration is:

LANG en_gb
BROWSER_TIMEOUT 120000

Did I miss something? Thanks :)

**Comment by ilike2burnthing** [comment] 2024-04-12 22:42
It's an open issue.

**Comment by ilike2burnthing** [comment] 2024-04-15 23:28
If the challenge is completed successfully in FlareSolverr for multiple indexers, is successful in Jackett but not Prowlarr, and both Jackett and Prowlarr are configured identically in Docker, then it points to some sort of issue with Prowlarr, although one I can't replicate.

Feel free to contact Prowlarr on their Discord to troubleshoot with them further, and point them to this issue.

**Closed by ilike2burnthing** 2024-04-15 23:28 UTC
Labels: more information needed

**Comment by spamoi33** [comment] 2024-04-16 10:16
Hello, I had this problem too. I managed to resolve it by removing the Flaresolver from Prowlarr's configuration and then putting it back with the tag. I then added YGGtorrent with the flaresolverr tag, and the connection was made.
