### ISSUE TITLE
close suddently windows 10

### ISSUE THREAD

**Issue by 3xploiton3** [FlareSolverr/FlareSolverr#224] opened 2021-11-19 18:08 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 2.0.2
* **Last working FlareSolverr version**:
* **Operating system**: windows
* **Are you using Docker**: [no]
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [no]
* **Are you using Captcha Solver:** [no]
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots
![(03;01;03)-20-November-2021-WIN10-SKYLAKE](https://user-images.githubusercontent.com/19517680/142670332-2655a497-c84a-444d-88ed-e32bc02642a6.gif)

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment] 2021-11-20 04:53
Are you using an AV which does https scanning?

**Comment by 3xploiton3** [comment] 2021-11-21 12:35
@ilike2burnthing Kaspersky cloud protection,
I already tried disable & exit AV,    result same

**Comment by ngosang** [comment] 2021-11-21 19:13
@3xploiton3 when FlareSolverr start it tries to open https://www.google.com to test everything is fine. Could you check if that URL is working in your regular web browser? Maybe I should make it configurable.

![image](https://user-images.githubusercontent.com/10577978/142775732-829a9ba5-863b-4acf-944f-646d816828dc.png)

**Comment by ilike2burnthing** [comment] 2021-11-22 02:06
Add Kaspersky's certificate - https://support.kaspersky.com/14620

**Comment by 3xploiton3** [comment] 2021-12-05 11:07
> @3xploiton3 when FlareSolverr starts it tries to open https://www.google.com to test everything is fine. Could you check if that URL is working in your regular web browser? Maybe I should make it configurable.
> 
> ![image](https://user-images.githubusercontent.com/10577978/142775732-829a9ba5-863b-4acf-944f-646d816828dc.png)

![image](https://user-images.githubusercontent.com/19517680/144743992-0da354da-0dfa-4a4d-8016-a15a74b67781.png)

**Comment by ilike2burnthing** [comment] 2021-12-05 13:01
Did adding Kaspersky's certificate not work?

**Comment by 3xploiton3** [comment] 2021-12-06 00:43
> Did adding Kaspersky's certificate not work?

no, doesn't work sir

![image](https://user-images.githubusercontent.com/19517680/144770898-d0fca111-4542-49c4-ad1f-092d7ae792af.png)

**Comment by ilike2burnthing** [comment] 2021-12-06 01:17
As a test:

> Kaspersky > Settings (cog wheel, bottom left) > Network settings > Encrypted connection scanning > select - Do not scan encrypted connections > Save

> ... > Network settings > Mozilla Firefox and Thunderbird > uncheck - Scan secure traffic in Mozilla applications > Save

Then try launching FlareSolverr again, see if that makes a difference.

Why are you running FlareSolverr in your installed Firefox folder?

**Comment by ngosang** [comment] 2021-12-08 19:26
I don't know if this is the cause but I will make the test URl configurable in #240

**Comment by ngosang** [comment] 2021-12-12 16:13
Fixed in FlareSolverr 2.1.0
You can set the environment variable `TEST_URL=https://www.google.com`

**Closed by ngosang** 2021-12-12 16:13 UTC
Labels: more information needed
