### ISSUE TITLE
Error flaresolverr

### ISSUE THREAD

**Issue by Moise77100** [FlareSolverr/FlareSolverr#1180] opened 2024-05-05 21:09 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.17
- Last working FlareSolverr version:3.3.17
- Operating system: UNRAID
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I have followed the resolution of this problem but I still have the same error message 
( https://github.com/FlareSolverr/FlareSolverr#environment-variables)

### Logged Error Messages

```text
2024-05-05 23:01:10 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
POST 500 Internal Server Error
```

**Comment by ilike2burnthing** [comment] 2024-05-05 21:11
Basically no information here to be able to help you, but I'm going to take a wild guess and say YGGtorrent and it's yet another duplicate of https://github.com/FlareSolverr/FlareSolverr/issues/1036.

**Closed by ilike2burnthing** 2024-05-05 21:11 UTC

**Comment by tifo71** [comment] 2024-06-21 01:10
this problem is back with YGG

2024-06-21 03:06:33 INFO     Challenge detected. Title found: Just a moment...
2024-06-21 03:07:32 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-06-21 03:07:32 INFO     Response in 60.746 s
2024-06-21 03:07:32 INFO   500 Internal Server Error

increasing the timing changes nothing. Is it a Flaresolverr problem ?

**Comment by PrzemekSkw** [comment] 2024-07-20 16:48
Hi, another time torrentleech.pl stops working

![image](https://github.com/user-attachments/assets/fcd78b45-e8b0-4dd1-af90-13390fa02a94)
