### ISSUE TITLE
Challenge detected. Selector found: .lds-ring

### ISSUE THREAD

**Issue by AARON8888** [FlareSolverr/FlareSolverr#1362] opened 2024-09-26 10:13 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: I don´t remember well.
- Operating system: Windows-10-10.0.19045-SP0
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint):Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] yes
- Are you using a Proxy: [yes/no] yes
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I have 8 indexers which are running with cloudflare challenge, and I use Jackett in it.

Any of them pass cloudflare challenge with flaresolverr.exe since two months at least, specially with the last FlareSolverr version 3.3.21?

Any idea how to solve this issue?

See above full log of one of indexers ([Il Corsaro Blu](https://ilcorsaroblu.org/))
[full log.txt](https://github.com/user-attachments/files/17146622/full.log.txt)

### Logged Error Messages

```text
Log from FlareSolverr.exe from cmd:

2024-09-26 11:49:10 INFO     FlareSolverr 3.3.21
2024-09-26 11:49:10 INFO     Testing web browser installation...
2024-09-26 11:49:10 INFO     Platform: Windows-10-10.0.19045-SP0
2024-09-26 11:49:10 INFO     Chrome / Chromium path: C:\ProgramData\flaresolverr\chrome\chrome.exe
2024-09-26 11:49:10 INFO     Chrome / Chromium major version: 123
2024-09-26 11:49:10 INFO     Launching web browser...
2024-09-26 11:49:51 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
2024-09-26 11:49:51 INFO     Test successful!
2024-09-26 11:49:51 INFO     Serving on http://0.0.0.0:8191

2024-09-26 12:03:55 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://ilcorsaroblu.org/index.php?page=torrents&category=0&options=0&active=0&order=3&by=2', 'proxy': {'url': 'http://xxx:xxx', 'username': 'xxx', 'password': 'xxx'}}
2024-09-26 12:04:00 INFO     Challenge detected. Selector found: .lds-ring
2024-09-26 12:04:53 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-09-26 12:04:53 INFO     Response in 57.195 s
2024-09-26 12:04:53 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

**Comment by Boosteed** [comment] 2024-09-26 12:42
Hello,

Same problem here, using deluge instead of jackett. Since yesterday night.

![image](https://github.com/user-attachments/assets/40b2723f-271c-433b-9483-288f4ca50946)

**Comment by jstaubr** [comment] 2024-09-26 12:48
This was already opened [yesterday](https://github.com/FlareSolverr/FlareSolverr/issues/1362), but was marked as duplicate without a reference to other issue which it should be a duplicate of 🤷‍♂️

**Comment by ilike2burnthing** [comment] 2024-09-27 03:39
Yes @jstaubr, if people have clearly put no effort into checking older issues, despite ticking a box saying they have done exactly that, then I'm not going to put any (more) effort into helping them.

**Closed by ilike2burnthing** 2024-09-27 03:39 UTC
