### ISSUE TITLE
Error solving the challenge, will always timeout. Ends with 500 Internal Server Error.

### ISSUE THREAD

**Issue by remy4409** [FlareSolverr/FlareSolverr#1219] opened 2024-06-20 16:44 UTC
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.19
- Last working FlareSolverr version:3.3.19
- Operating system: Docker Unraid
- Are you using Docker: Yes
- FlareSolverr User-Agent (see log traces or / endpoint):Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: No
- Are you using a Proxy: No
- Are you using Captcha Solver: No
- If using captcha solver, which one:
- URL to test this issue: https://www.ygg.re/
```

### Description

Using flaresolverr with Jacket on unraid docker, requests will always timeout. It was working fine yesterday and then stopped today. Seems to be the same issue that was present in early May of 2024, which was fixed with the ENV LANG. I didn't changed anything to my config since that fix.

### Logged Error Messages

```text
2024-06-20 16:40:00 INFO Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?do=search&order=desc&sort=publish_date&category=all'}
version_main cannot be converted to an integer
2024-06-20 16:40:01 INFO Challenge detected. Title found: Just a moment...
2024-06-20 16:40:01 INFO Challenge detected. Title found: Just a moment...
2024-06-20 16:41:00 ERROR Error: Error solving the challenge. Timeout after 60.0 seconds.

2024-06-20 16:41:00 INFO Response in 60.843 s
2024-06-20 16:41:00 INFO 172.17.0.1 POST http://192.168.1.5:8191/v1 500 Internal Server Error
```

**Comment by eouti** [comment] 2024-06-20 16:50
same issue here

**Comment by remy4409** [comment] 2024-06-20 16:54
Actually saw issue 1036 and went through it, but have not find a clear answer as to what the problem might be and how to solve it.

**Comment by elchusco** [comment] 2024-06-20 17:10
#1036

**Comment by remy4409** [comment] 2024-06-20 17:19
> #1036

Yes, I read it entirely, but I wasn't able to figure out if a solution was found. Quoting [ilike2burnthing](https://github.com/ilike2burnthing): 

> This was the same behaviour seen with yggtorrent, which was resolved by adding the ENV LANG and using an English language code, however I've tried several language codes to no success.

I did it that once and it solved it, but the issue is now back, so I don't think it's related.

**Comment by 0rsa** [comment] 2024-06-20 17:26
Same here

> 2024-06-20 18:20:36 INFO     ReqId 140713823463104 Response in 60.742 s
> 2024-06-20 18:20:36 INFO     ReqId 140713823463104 172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error

It works again setting env LANG to 'fr-FR'
Thank you

**Comment by elchusco** [comment] 2024-06-20 17:27
Yes, I tried it too, but didn't worked. Logs says the challenge is not even detected. But what I noticed, is that when I try to access a webpage protected by Cloudflare and that I refresh the page multiple times (w/out resolving challenge) it takes longer and longer to get the checkbox. Like if I was delayed each time. Might be related to what flaresolverr is facing.

**Closed** 2024-06-20 17:28 UTC

**Comment by remy4409** [comment] 2024-06-20 17:36
> Same here
> 
> > 2024-06-20 18:20:36 INFO     ReqId 140713823463104 Response in 60.742 s
> > 2024-06-20 18:20:36 INFO     ReqId 140713823463104 172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error
> 
> It works again setting env LANG to 'fr-FR' Thank you

Not working for me, it cannot find challenge when set to fr-FR.

**Comment by 0rsa** [comment] 2024-06-20 17:40
I confirm, I was happy too early seeing a 200 response status instead of a timeout and a 500 response status
the challenge is also now not detected from my side

**Comment by John5798** [comment] 2024-06-20 17:49
Same here

**Comment by ilike2burnthing** [comment] 2024-06-20 18:34
As already mentioned above, this is just a duplicate of #1036.

**Comment by remy4409** [comment] 2024-06-20 18:41
> As already mentioned above, this is just a duplicate of #1036.

Is there an explanation as to why it was working with the fixes previously and then it just stopped without any change to our config?

**Comment by ilike2burnthing** [comment] 2024-06-20 18:51
Previously a French IP was enough to not get a challenge, then an English language LANG ENV was enough to prevent looping challenges, now they've seemingly gone the way of many other sites and are using stricter blocking.

You can find a test image from a contributor in the discussion in https://github.com/FlareSolverr/FlareSolverr/pull/1163, however it has issues with memory usage (hence not just linking directly to it - if someone isn't going to bother reading, I'm not going start trying to troubleshoot with them when something goes wrong).

**Comment by remy4409** [comment] 2024-06-20 19:44
> Previously a French IP was enough to not get a challenge, then an English language LANG ENV was enough to prevent looping challenges, now they've seemingly gone the way of many other sites and are using stricter blocking.
> 
> You can find a test image from a contributor in the discussion in #1163, however it has issues with memory usage (hence not just linking directly to it - if someone isn't going to bother reading, I'm not going start trying to troubleshoot with them when something goes wrong).

You mean the image by [21hsmw](https://github.com/21hsmw)? I've been running on it since May, and it stopped working today.

**Comment by remy4409** [comment] 2024-06-20 19:57
@ilike2burnthing I just tried running it on windows and it's working fine, the issue indeed seems to be isolated to docker.

**Comment by g0ldyy** [comment] 2024-06-20 23:11
switch to docker.io/21hsmw/flaresolverr:nodriver, this just fixed all my issues.
nodriver > undetected_chromedriver

**Comment by screamjojo** [comment] 2024-06-20 23:19
> switch to docker.io/21hsmw/flaresolverr:nodriver, this just fixed all my issues. nodriver > undetected_chromedriver

Thank you but when I try to download I've got: "failed to register layer: ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header"
Have you a solution ?

**Comment by g0ldyy** [comment] 2024-06-20 23:25
> > switch to docker.io/21hsmw/flaresolverr:nodriver, this just fixed all my issues. nodriver > undetected_chromedriver
> 
> Thank you but when I try to download I've got: "failed to register layer: ApplyLayer exit status 1 stdout: stderr: archive/tar: invalid tar header" Have you a solution ?

I'm using docker: docker pull docker.io/21hsmw/flaresolverr:nodriver

**Comment by screamjojo** [comment] 2024-06-20 23:29
> > > switch to docker.io/21hsmw/flaresolverr:nodriver, this just fixed all my issues. nodriver > undetected_chromedriver
> > 
> > 
> > Thank you but when I try to download I've got: "failed to register layer: ApplyLayer exit status 1 stdout: stderr: archive/tar: invalid tar header" Have you a solution ?
> 
> I'm using docker: docker pull docker.io/21hsmw/flaresolverr:nodriver

me too ! I don't understand ...

**Comment by g0ldyy** [comment] 2024-06-20 23:33
> failed to register layer: ApplyLayer exit status 1 stdout: stderr: archive/tar: invalid tar header

good luck solving the problem, but I guarantee that if you manage to install it, you won't have any problem anymore
nodriver is the successor of undetected_chromedriver that jackett uses, and it's so much faster and undetected

**Comment by remy4409** [comment] 2024-06-20 23:47
> > switch to docker.io/21hsmw/flaresolverr:nodriver, this just fixed all my issues. nodriver > undetected_chromedriver
> 
> Thank you but when I try to download I've got: "failed to register layer: ApplyLayer exit status 1 stdout: stderr: archive/tar: invalid tar header" Have you a solution ?

Same thing for me.

**Comment by remy4409** [comment] 2024-06-21 00:17
@screamjojo Are you running Unraid? What version?

**Comment by sodanexus** [comment] 2024-06-21 00:57
Same thing for me on synology

**Comment by 0rsa** [comment] 2024-06-21 03:45
@g0ldyy still the same issue using your image unfortunately with Docker on Debian

> 2024-06-21 04:41:23 INFO     ReqId 139827299277696 FlareSolverr 3.4.0
> 2024-06-21 04:41:23 DEBUG    ReqId 139827299277696 Debug log enabled
> 2024-06-21 04:41:23 INFO     ReqId 139827299277696 Testing web browser installation...
> 2024-06-21 04:41:23 INFO     ReqId 139827299277696 Platform: Linux-6.1.0-13-amd64-x86_64-with-glibc2.36
> 2024-06-21 04:41:23 INFO     ReqId 139827299277696 Chrome / Chromium path: /usr/bin/chromium
> 2024-06-21 04:41:23 INFO     ReqId 139827299277696 Chrome / Chromium major version: 125
> 2024-06-21 04:41:23 INFO     ReqId 139827299277696 Launching web browser...
> 2024-06-21 04:41:23 DEBUG    ReqId 139827299277696 Launching web browser with undetected-chromedriver...
> version_main cannot be converted to an integer
> 2024-06-21 04:41:23 DEBUG    ReqId 139827299277696 Started executable: `/app/chromedriver` in a child process with pid: 31
> 2024-06-21 04:41:24 INFO     ReqId 139827299277696 FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
> 2024-06-21 04:41:24 INFO     ReqId 139827299277696 Test successful!
> 2024-06-21 04:41:24 INFO     ReqId 139827299277696 Serving on http://0.0.0.0:8191

> 2024-06-21 04:43:33 DEBUG    ReqId 139827022395072 Waiting for title (attempt 37): Just a moment...
> 2024-06-21 04:43:34 DEBUG    ReqId 139827022395072 Timeout waiting for selector
> 2024-06-21 04:43:34 DEBUG    ReqId 139827022395072 Try to find the Cloudflare verify checkbox...
> 2024-06-21 04:43:34 DEBUG    ReqId 139827022395072 Cloudflare verify checkbox not found on the page.
> 2024-06-21 04:43:34 DEBUG    ReqId 139827022395072 Try to find the Cloudflare 'Verify you are human' button...
> 2024-06-21 04:43:34 DEBUG    ReqId 139827022395072 The Cloudflare 'Verify you are human' button not found on the page.
> 2024-06-21 04:43:35 DEBUG    ReqId 139827263936192 A used instance of webdriver has been destroyed

**Comment by John5798** [comment] 2024-06-21 05:51
@g0ldyy Thank you sm! Works flawlessly now

**Comment by ilike2burnthing** [comment] 2024-06-21 07:57
Again, that image has memory issues of its own. If you haven't read the discussion in https://github.com/FlareSolverr/FlareSolverr/pull/1163, you shouldn't be using it (and given that a user there had trouble pulling the image, I'm going to guess people haven't done so).

**Comment by John5798** [comment] 2024-06-21 09:01
I've got 64 gigs of memory to spare, no biggie really

**Comment by g0ldyy** [comment] 2024-06-21 09:24
> Again, that image has memory issues of its own. If you haven't read the discussion in #1163, you shouldn't be using it (and given that a user there had trouble pulling the image, I'm going to guess people haven't done so).

it may have memory problems but it's the only alternative that works. flaresolverr no longer works at all on any sites protected by cloudflare for me.
why do you stay on undetected_chromedriver when nodriver exists?

**Comment by ilike2burnthing** [comment] 2024-06-21 09:32
Because the memory leak that currently exists (by nodriver, not FlareSolverr) is capable of quickly crashing systems (yes, eventually even those with 64GB of RAM).

It's available for people who want to test it, understanding the risk involved. It definitely shouldn't just be offered up to users with no context.

**Comment by sodanexus** [comment] 2024-06-21 15:57
> Because the memory leak that currently exists (by nodriver, not FlareSolverr) is capable of quickly crashing systems (yes, eventually even those with 64GB of RAM).
> 
> It's available for people who want to test it, understanding the risk involved. It definitely shouldn't just be offered up to users with no context.

In the meantime, while waiting for a fix, is it possible to have a 'beta' version for those who are aware of the situation? The 21hsmw version doesn't want to install with Docker

**Comment by ilike2burnthing** [comment] 2024-06-21 16:30
@21hsmw a few more people are having issues successfully pulling/extracting the image. Any idea what the issue would be?

As other images work, I don't think it's a network or device (e.g. downloads being corrupted). Obviously it's not exactly this, but what comes to mind is when RAR5 came out and wasn't compatible with older systems and software. Is there something 'too new' being used?

**Comment by 21hsmw** [comment] 2024-06-21 16:44
> @21hsmw a few more people are having issues successfully pulling/extracting the image. Any idea what the issue would be?
> 
> As other images work, I don't think it's a network or device (e.g. downloads being corrupted). Obviously it's not exactly this, but what comes to mind is when RAR5 came out and wasn't compatible with older systems and software. Is there something 'too new' being used?

No idea, to be honest. I've tried to replicate the problem on a couple of different systems I have my hands on and haven't gotten the same thing. Unfortunately, the error message is not very explicit and it could be happening for a lot of different reasons.
I will rebuild and push a new image just in case.

**Comment by sodanexus** [comment] 2024-06-21 20:19
Okay, thanks. The installation is now possible. Everything works well; indeed, "nodriver" is clearly faster and all my tests are conclusive. In the meantime, while waiting for a proper version, we shouldn't forget to restart it from time to time to avoid a significant memory leak. Is that correct? Good luck, anyway; I have no doubt that you will succeed.

**Comment by ilike2burnthing** [comment] 2024-06-21 21:27
[v3.3.20](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.20)

**Comment by screamjojo** [comment] 2024-06-21 22:45
work like a charm !!! thank @ilike2burnthing !!!!!!

**Comment by romquenin** [comment] 2024-06-22 14:32
Thank you @ilike2burnthing

**Comment by raffi78** [comment] 2024-07-04 13:02
hi
V3.3.21 same issue
